import Head from 'next/head';
import Image from 'next/image';
import kirby from '../public/kirbyheadphoneblend-crop.png';
import Link from 'next/link';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {GrSystem} from 'react-icons/gr';
import {MdWeb} from 'react-icons/md';
import {MdOutlineBrush} from 'react-icons/md';
import {RiListSettingsFill} from 'react-icons/ri';
import medrawing from '../public/me_drawing.png';
import mefish from '../public/hannahfish.png';
import {AiFillLinkedin, AiFillGithub, AiOutlineMail}  from 'react-icons/ai';

function About() {
  return (
    <div>
        <Head>
            <title>Hannah McGowan Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>


        <main className="px-10 md:px-20 lg:px-40">
          <nav className="py-10 max-w-screen-xl flex flex-wrap justify-between mx-auto items-center text-slate-900 dark:text-white">
              <Link href="/"><h1 className="text-xl font-pixel text-slate-900">HM:H+M</h1></Link>
              <div className="w-full md:block md:w-auto">
                <ul className="flex items-center text-slate-900">
                  <li><Link href="/work" className="ml-8 font-semibold hover:text-light-blue-500 active:text-light-blue-800">WORK</Link></li>
                  <li><Link href="/about" className="ml-8 font-semibold hover:text-light-blue-500 active:text-light-blue-800">ABOUT</Link></li>
                  <li><Link href="/gallery" className="ml-8 font-semibold hover:text-light-blue-500 active:text-light-blue-800">GALLERY</Link></li>
                </ul>
              </div>
          </nav>
            <div className="text-center pb-10">
              <h1 className="text-4xl pb-5 text-slate-900">about me</h1>
              <p className="text-lg text-slate-400">who am i? where do i come from? where do i go?</p>
            </div>
            {/* had lg:items-center in classname below to center text with center of image 
            had justify-center too but idk what that did*/}
            <div className="pb-20 pt-10 lg:flex lg:justify-center lg:space-x-10">
                <div className="lg:w-1/2 lg:px-5">
                    <ul className="leading-8 marker:text-light-blue-600 text-slate-700 font-light pl-5">
                      <li><span className="text-light-blue-600 font-semibold">Intro: </span>Hi, I'm Hannah! From the bay area, looking for a job, have too many hobbies</li>
                      <li><span className="text-light-blue-600 font-semibold">Education: </span>
                      Graduated from UC Berkeley in 2022 with degrees in Cognitive Science and Economics
                      <ul className="list-disc leading-6 marker:text-light-blue-600 text-slate-700 font-light pl-5 text-sm">
                        <li>I studied CogSci because I found studying the brain - in all its facets - so fascinating. The Economics part was more random, I just wanted to know what people were saying when talking about stocks (jokes on me I still don't know)</li>
                      </ul>
                      </li>
                      <li><span className="text-light-blue-600 font-semibold">Music: </span>I really like music. I'm always finding new genres, languages, and vibes to obssess over. 
                      <ul className="list-disc leading-6 marker:text-light-blue-600 text-slate-700 font-light pl-5 text-sm">
                        <li>I’ve dabbled around with max 8, original comps on the piano, garageband for years and have recently graduated up to FLStudio (free version :D) </li>
                      </ul>
                      </li>
                    </ul>
                    <div className="py-6 text-center">
                      <a href="/HannahMcGowan_Resume.pdf" target="_blank" className="bg-gradient-to-r from-cyan-800 to-blue-400 text-white px-4 py-2 rounded-md">Resume</a>
                    </div>
                </div>
                <div className="lg:px-5">
                <Image src={mefish} width={350} height={350} alt="picture of me with fisheye lens" className="mx-auto"/>
                </div>
            </div>
            <div>
              <div className="text-5xl mx-auto flex justify-center gap-16 py-1 text-slate-300  dark:text-slate-600">
                <a href="https://www.linkedin.com/in/hannah-m-74b800120" target="_blank"> <AiFillLinkedin /> </a>
                <a href="https://github.com/hannahmcg" target="_blank">  <AiFillGithub /> </a>
                <a href="mailto:hannahcmcg@berkeley.edu"> <AiOutlineMail /> </a>
              </div> 
            </div>
            <div className="py-10 mt-10 mb-10">
              <iframe className="rounded-xl mx-auto" src="https://open.spotify.com/embed/playlist/613PD49YymDxtoW5FMMa4a?utm_source=generator" width="90%" height="352" frameBorder="0" allowFullScreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
            </div>
            {/*
            <section>
              <div>
                <h3 className="text-3xl text-slate-900 py-10  dark:text-slate-300">my experience: design & dev</h3>
                <p className="text-md py-2 leading-8 text-slate-700 dark:text-slate-400">The beginning of my journey 
                as a developer started in my university, doing projects for various classes and organizations. My most notable project in that time was 
                for the <span className="text-blue-400">Cognitive Science Student Association</span>. I also have experience in UI/UX <span className="text-blue-400">
                  designing products</span> with other groups. I started with just learning HTML, CSS, and JS from youtube and have since grown accustomed with 
                  react, next, tailwind, material tailwind, and continue to look out for the best methods of development. 
                </p>
              </div>
              <div className="lg:flex gap-10 items-center">
                <div className="lg:w-1/3 text-center shadow-lg  dark:shadow-blue-500 p-10 rounded-xl my-10">
                  <MdOutlineBrush className="mx-auto text-5xl text-slate-800 dark:text-slate-400"/>
                  <h3 className="text-lg font-medium pt-8 pb-2 text-slate-900 dark:text-slate-300">innovative designs</h3>
                  <p className="py-2 text-slate-800 dark:text-slate-400">create cool designs in a variety of art mediums</p>
                  <h4 className="py-4 text-blue-400">design tags</h4>
                  <p className="text-slate-500  dark:text-slate-400 py-1">Figma, Adobe XD</p>
                  <p className="text-slate-500  dark:text-slate-400 py-1">Illustrator, Photoshop</p>
                  <p className="text-slate-500  dark:text-slate-400 py-1">Autodesk Maya, Blender</p>
                </div>
                <div className="lg:w-1/3 text-center shadow-lg dark:shadow-blue-500 p-10 rounded-xl my-10">
                  <MdWeb className="mx-auto text-5xl text-slate-800 dark:text-slate-400"/>
                  <h3 className="text-lg font-medium pt-8 pb-2 text-slate-900 dark:text-slate-300">frontend apps</h3>
                  <p className="py-2 text-slate-800 dark:text-slate-400">build clean designs using modern platforms with UI/UX lense</p>
                  <h4 className="py-4 text-blue-400">languages/packages</h4>
                  <p className="text-slate-500  dark:text-slate-400 py-1">Javascript, react.js, next.js</p>
                  <p className="text-slate-500  dark:text-slate-400 py-1">CSS, tailwindcss, material tw</p>
                  <p className="text-slate-500  dark:text-slate-400 py-1">HTML</p>
                </div>
                <div className="xl:w-1/3 text-center shadow-lg  dark:shadow-blue-500 p-10 rounded-xl my-10">
                  <RiListSettingsFill className="mx-auto text-5xl text-slate-800 dark:text-slate-400"/>
                  <h3 className="text-lg font-medium pt-8 pb-2 text-slate-900 dark:text-slate-300">backend dev</h3>
                  <p className="py-2 text-slate-800 dark:text-slate-400">build concise and easily legible code and models</p>
                  <h4 className="py-4 text-blue-400">languages</h4>
                  <p className="text-slate-500  dark:text-slate-400 py-1">python</p>
                  <p className="text-slate-500  dark:text-slate-400 py-1">java</p>
                  <p className="text-slate-500  dark:text-slate-400 py-1">SQL, pandas</p>
                </div>
              </div>
            </section>
          */}
        </main>
    </div>
  )
}

export default About