import Head from 'next/head';
import Image from 'next/image';
import kirby from '../public/kirbyheadphoneblend-crop.png';
import Link from 'next/link';
import {BsFillMoonStarsFill} from 'react-icons/bs';

function About() {
  return (
    <div>
        <Head>
            <title>Hannah McGowan Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <nav className="pt-10 px-25 mb-6 flex justify-between text-slate-900 dark:text-white">
            <h1 className="text-xl font-pixel text-cyan-800">HM:H+M</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill 
                onClick={() => setDarkMode(!darkMode)} 
                className="cursor-pointer text-2xl"/>
              </li>
              <li><Link href="/about" className="ml-5">About</Link></li>
              <li><Link href="/work" className="ml-5">Work</Link></li>
            </ul>
        </nav>

        <Link href="/" className="text-center px-20">Home</Link>

        <main className="p-10 w-screen">
            <div className="flex items-center justify-center">
                <div className="px-2">
                    <h1>About Me</h1>
                    <p>Hi I'm hannah. I like things and things and I'm interested in things and I like a lot of things.</p>
                    <p>This where i went to school and what I studied. This is cool stuff I do and like to do as hobbies or interests.</p>
                </div>
                <div className="relative h-80 w-80 md:h-90 md:w-90">
                <Image src={kirby} className="object-cover" fill alt="3d kirby with headphones render"/>
                </div>
            </div>
        </main>
    </div>
  )
}

export default About