import Head from 'next/head';
import Image from 'next/image';
import kirby from '../public/kirbyheadphoneblend-crop.png';
import Link from 'next/link';
import {BsFillMoonStarsFill} from 'react-icons/bs';

function About() {
  return (
    <div>
        <Head>
            <title>Hannah McGowan Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <nav className="p-10 max-w-screen-xl flex flex-wrap justify-between mx-auto items-center text-slate-900 dark:text-white">
            <h1 className="text-xl font-pixel text-cyan-800">HM:H+M</h1>
            <div className="w-ful md:block md:w-auto">
              <ul className="flex items-center">
                <li>
                  <BsFillMoonStarsFill 
                  onClick={() => setDarkMode(!darkMode)} 
                  className="cursor-pointer text-2xl"/>
                </li>
                <li><Link href="/" className="ml-5">Home</Link></li>
                <li><Link href="/about" className="ml-5">About</Link></li>
                <li><Link href="/work" className="ml-5">Work</Link></li>
              </ul>
            </div>
        </nav>

        <main className="p-10 w-screen">
            <div className="flex items-center justify-center">
                <div className="px-2">
                    <h1>About Me</h1>
                    <p>Hi I'm hannah. I like things and things and I'm interested in things and I like a lot of things.</p>
                    <p>This where i went to school and what I studied. This is cool stuff I do and like to do as hobbies or interests.</p>
                </div>
                <div className="relative h-80 w-80 md:h-90 md:w-90">
                <Image src={kirby} className="object-cover" fill alt="3d kirby with headphones render"/>
                </div>
            </div>
            <section>
          <div>
            <h3 className="text-3xl text-slate-900 py-10  dark:text-slate-300">my experience: design & dev</h3>
            <p className="text-md py-2 leading-8 text-slate-700 dark:text-slate-400">The beginning of my journey 
            as a developer started in my university, doing projects for various classes and organizations. My most notable project in that time was 
            for the <span className="text-blue-400">Cognitive Science Student Association</span>. I also have experience in UI/UX <span className="text-blue-400">
              designing products</span> with other groups. I started with just learning HTML, CSS, and JS from youtube and have since grown accustomed with 
              react, next, tailwind, material tailwind, and continue to look out for the best methods of development. 
            </p>
          </div>
          <div className="lg:flex gap-10 items-center">
            <div className="lg:w-1/3 text-center shadow-lg  dark:shadow-blue-500 p-10 rounded-xl my-10">
              {/*<Image src={design} width={100} height={100} className="mx-auto" />*/}
              <MdOutlineBrush className="mx-auto text-5xl text-slate-800 dark:text-slate-400"/>
              <h3 className="text-lg font-medium pt-8 pb-2 text-slate-900 dark:text-slate-300">innovative designs</h3>
              <p className="py-2 text-slate-800 dark:text-slate-400">create cool designs in a variety of art mediums</p>
              <h4 className="py-4 text-blue-400">design tags</h4>
              <p className="text-slate-500  dark:text-slate-400 py-1">Figma, Adobe XD</p>
              <p className="text-slate-500  dark:text-slate-400 py-1">Illustrator, Photoshop</p>
              <p className="text-slate-500  dark:text-slate-400 py-1">Autodesk Maya, Blender</p>
            </div>
            <div className="lg:w-1/3 text-center shadow-lg dark:shadow-blue-500 p-10 rounded-xl my-10">
              <MdWeb className="mx-auto text-5xl text-slate-800 dark:text-slate-400"/>
              <h3 className="text-lg font-medium pt-8 pb-2 text-slate-900 dark:text-slate-300">frontend apps</h3>
              <p className="py-2 text-slate-800 dark:text-slate-400">build clean designs using modern platforms with UI/UX lense</p>
              <h4 className="py-4 text-blue-400">languages/packages</h4>
              <p className="text-slate-500  dark:text-slate-400 py-1">Javascript, react.js, next.js</p>
              <p className="text-slate-500  dark:text-slate-400 py-1">CSS, tailwindcss, material tw</p>
              <p className="text-slate-500  dark:text-slate-400 py-1">HTML</p>
            </div>
            <div className="xl:w-1/3 text-center shadow-lg  dark:shadow-blue-500 p-10 rounded-xl my-10">
              <RiListSettingsFill className="mx-auto text-5xl text-slate-800 dark:text-slate-400"/>
              <h3 className="text-lg font-medium pt-8 pb-2 text-slate-900 dark:text-slate-300">backend dev</h3>
              <p className="py-2 text-slate-800 dark:text-slate-400">build concise and easily legible code and models</p>
              <h4 className="py-4 text-blue-400">languages</h4>
              <p className="text-slate-500  dark:text-slate-400 py-1">python</p>
              <p className="text-slate-500  dark:text-slate-400 py-1">java</p>
              <p className="text-slate-500  dark:text-slate-400 py-1">SQL, pandas</p>
            </div>
          </div>
        </section>
        </main>
    </div>
  )
}

export default About