import Head from 'next/head';
import Image from 'next/image';
import kirby from '../public/kirbyheadphoneblend-crop.png';
import Link from 'next/link';
import {BsFillMoonStarsFill} from 'react-icons/bs';

function About() {
  return (
    <div className="p-10 w-screen" >
        <Head>
            <title>Hannah McGowan Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        
        <nav className="pt-10 mb-6 flex justify-between text-slate-900 dark:text-white">
            <h1 className="text-xl font-pixel text-cyan-800">HM:H+M</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill 
                onClick={() => setDarkMode(!darkMode)} 
                className="cursor-pointer text-2xl"/>
              </li>
              <li><a href="/HannahMcGowan_Resume.pdf" target="_blank" className="bg-gradient-to-r from-cyan-800 to-blue-400 text-white px-4 py-2 rounded-md ml-8">Resume</a></li>
              <li><Link href="/about" className="ml-5">About</Link></li>
              <li><Link href="/work" className="ml-5">Work</Link></li>
            </ul>
          </nav>
        <Link href="/" className="text-center">Home</Link>

        <div className="flex items-center justify-center">
            <div className="px-2">
                <h1>About Me</h1>
                <p>Hi I'm hannah. I like things and things and I'm interested in things and I like a lot of things.</p>
                <p>This where i went to school and what I studied. This is cool stuff I do and like to do as hobbies or interests.</p>
            </div>
            <div className="relative h-80 w-80 md:h-90 md:w-90">
            <Image src={kirby} className="object-cover" fill alt="3d kirby with headphones render"/>
            </div>
        </div>
    </div>
  )
}

export default About