import Head from 'next/head';
import Image from 'next/image';
import kirby from '../public/kirbyheadphoneblend-crop.png';
import Link from 'next/link';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {GrSystem} from 'react-icons/gr';
import {MdWeb} from 'react-icons/md';
import {MdOutlineBrush} from 'react-icons/md';
import {RiListSettingsFill} from 'react-icons/ri';
import medrawing from '../public/me_drawing.png';
import mefish from '../public/hannahfish.png';
import {AiFillLinkedin, AiFillGithub, AiOutlineMail}  from 'react-icons/ai';
import NavMain from '../components/Nav.js';
import hannahcar from '../public/hannahcar.JPG';

function About() {
  return (
    <div>
        <Head>
            <title>Hannah McGowan Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/kirbyicon.png" />
        </Head>


        <NavMain />
        <main className="px-10 md:px-20 lg:px-40 pt-5">
            <div className="text-center pb-10">
              <h1 className="text-4xl pb-5 text-slate-900">about me</h1>
              <p className="text-lg text-slate-400">who am i? where do i come from? where do i go?</p>
            </div>
            {/* had lg:items-center in classname below to center text with center of image 
            had justify-center too but idk what that did*/}
          {/*
            <div className="pb-20 pt-10 lg:flex lg:justify-center lg:space-x-10">
                <div className="lg:w-1/2 lg:px-5">
                    <ul className="leading-8 marker:text-light-blue-600 text-slate-700 font-light pl-5">
                      <li><span className="text-light-blue-600 font-semibold">Intro: </span>Hi, I'm Hannah! From the bay area, looking for a job, have too many hobbies</li>
                      <li><span className="text-light-blue-600 font-semibold">Education: </span>
                      Graduated from UC Berkeley in 2022 with degrees in Cognitive Science and Economics
                      <ul className="list-disc leading-6 marker:text-light-blue-600 text-slate-700 font-light pl-5 text-sm">
                        <li>I studied CogSci because I found studying the brain - in all its facets - so fascinating. The Economics part was more random, I just wanted to know what people were saying when talking about stocks (jokes on me I still don't know)</li>
                      </ul>
                      </li>
                      <li><span className="text-light-blue-600 font-semibold">Music: </span>I really like music. I'm always finding new genres, languages, and vibes to obssess over. 
                      <ul className="list-disc leading-6 marker:text-light-blue-600 text-slate-700 font-light pl-5 text-sm">
                        <li>I’ve dabbled around with max 8, original comps on the piano, garageband for years and have recently graduated up to FLStudio (free version :D) </li>
                      </ul>
                      </li>
                    </ul>
                    <div className="py-6 text-center">
                      <a href="/HannahMcGowan_Resume.pdf" target="_blank" className="bg-gradient-to-r from-cyan-800 to-blue-400 text-white px-4 py-2 rounded-md">Resume</a>
                    </div>
                </div>
                <div className="lg:px-5">
                <Image src={mefish} width={350} height={350} alt="picture of me with fisheye lens" className="mx-auto"/>
                </div>
            </div>
          */}
        <div className="pb-20 pt-10">
          <div className="flex justify-center space-x-10 pb-10">
            <div className="md:w-[800px] md:flex text-center md:text-left">
            <div className="md:w-1/2 w-[200px] mx-auto pb-10 md:pb-0 pl-2">
              <Image className="rounded-lg" src={hannahcar} width={340} height={400} alt="picture of me at a racetrack"/>
            </div>
            <div className="md:w-1/2 text-slate-500 space-y-5 md:space-y-8">
              <p className="px-2">I’m <span className="text-light-blue-600">interdisciplinary</span> - I like doing and learning everything. Instead of seeing it as spreading myself thin, I'd say this is my greatest skill. The more I explore, the more intuitive and novel connections I find myself making. </p>
              <p className="px-2">I’m <span className="text-light-blue-600">perceptive</span> - I've studied human behavior in just about as many ways as you can think, especially in social settings (sincerely, a former people pleaser).</p>
              <p className="px-2">I’m <span className="text-light-blue-600">creative and curious</span> - Sometimes this results in me eating live octopus, face planting on a black diamond slope, or heavily regretting getting highlights in my hair. Or I become good at music production, pick up skills in 3D modeling, learn an entirely new programming language, or realize I have an affinity for anime.</p>
            </div>
            </div>
          </div>

          <div className="mt-10 text-center mx-20 text-slate-500 space-y-4">
            <h2 className="text-slate-700 text-2xl text-center">education</h2>
            <p className="italic text-lg pt-5">Degree in Cognitive Science from UC Berkeley </p>
            <p className="font-light text-sm">I studied CogSci because I found studying the brain, in all its facets, fascinating. There’s something unique about studying the thing we’re using to study - the more you try to think about it the more of a recursive loop you can get stuck in. CogSci is a great discipline because it emphasizes the value in looking at the brain through every possible lens.</p>
            <p className="italic text-lg pt-5">Degree in Economics from UC Berkeley </p>
            <p className="font-light text-sm">I ended up double majoring in Econ simply because I wanted to understand what people were saying when talking about stocks (jokes on me I still don't know). I did, however, get the chance to be exposed to many different aspects of Economics that I wouldn't have otherwise explored - like game theory or pretty much anything that had an emphasis on psychology and the impacts of human behavior. </p>
          </div>

          {/*<div className="mt-10 text-center mx-20 text-slate-500">
            <h2 className="text-slate-700 text-2xl text-center">interests</h2>
            <div className="flex flex-wrap">
              <p className="font-light text-md text-slate-500 p-10">piano</p>
              <p className="font-light text-md text-slate-500 p-10">music composition</p>
              <p className="font-light text-md text-slate-500 p-10">animal crossing</p>
              <p className="font-light text-md text-slate-500 p-10">film photography</p>
              <p className="font-light text-md text-slate-500 p-10">tea (and boba)</p>
              <p className="font-light text-md text-slate-500 p-10">piano</p>
              <p className="font-light text-md text-slate-500 p-10">piano</p>
              <p className="font-light text-md text-slate-500 p-10">piano</p>
              <p className="font-light text-md text-slate-500 p-10">piano</p>
            </div>
        </div> */}

          </div>

            <div>
              <div className="text-5xl mx-auto flex justify-center gap-16 py-1 text-slate-300  dark:text-slate-600">
                <a href="https://www.linkedin.com/in/hannah-m-74b800120" target="_blank"> <AiFillLinkedin /> </a>
                <a href="https://github.com/hannahmcg" target="_blank">  <AiFillGithub /> </a>
                <a href="mailto:hannahcmcg@berkeley.edu"> <AiOutlineMail /> </a>
              </div> 
            </div>
            <div className="py-10 mt-10 mb-10">
              <iframe className="rounded-xl mx-auto" src="https://open.spotify.com/embed/playlist/613PD49YymDxtoW5FMMa4a?utm_source=generator" width="90%" height="352" frameBorder="0" allowFullScreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
            </div>
            
        </main>
    </div>
  )
}

export default About