import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillLinkedin, AiFillGithub, AiOutlineMail}  from 'react-icons/ai';
import Image from 'next/image';
import kirby from '../public/kirbyheadphoneblend-crop.png';
import web4 from '../public/glossier.png';
import web2 from '../public/spotifyalbum.png';
import web3 from '../public/gallery.png';
import web1 from '../public/koss.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import {useState} from 'react';
import PortTabs from '../components/PortTabs.js';
import Link from 'next/link';
import NavMain from '../components/Nav.js';


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Hannah McGowan Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/kirbyicon.png" />
      </Head>

      <NavMain />
      <main className= "px-10 md:px-20 lg:px-40 pb-10 pt-20">
        <div className="text-center pb-10">
          <h1 className="text-4xl pb-5 text-slate-900">design + artwork</h1>
          <p className="text-lg text-slate-400">original UI designs and redesigns, artwork, creative explorations</p>
        </div>
        <section>
          <div>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              <div className="basis-1/3 flex-1">
                <Image src={web1} className="rounded-lg object-cover" 
                width={'100%'} height={'100%'} responsive="true" alt="koss web redesign"/>
              </div>
              <div className="basis-1/3 flex-1">
                <Image src={web2} className="rounded-lg object-cover" 
                width={'100%'} height={'100%'} responsive="true" alt="spotify album art web design"/>
              </div>
              <div className="basis-1/3 flex-1">
                <Image src={web3} className="rounded-lg object-cover" 
                width={'100%'} height={'100%'} responsive="true" alt="online gallery web design"/>
              </div>
              <div className="basis-1/3 flex-1">
                <Image src={web4} className="rounded-lg object-cover" 
                width={'100%'} height={'100%'} responsive="true" alt="glossier web redesign"/>
              </div>
            </div>
          </div>

        </section>
      </main>

    </div>
  )
}
