import Head from 'next/head';
import {useState} from 'react';
import NavMain from '../components/Nav.js';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Hannah McGowan's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/kirbyicon.png" />
      </Head>
      
      <main className= "min-h-screen  bg-gray-50">

      <NavMain />
        <section className="px-5 md:px-8 lg:px-10 pt-20 md:pt-5">

          <div className="pt-20 min-h-screen bg-blue-gray-100 my-4 mt-4 mb-20">
            <h1 className="text-6xl md:text-9xl pl-4">HANNAH MCG</h1>
            <div className="pl-5 md:pl-6">
              <h3>PORTFOLIO</h3>
              <h3>DIGITAL DESIGN</h3>
              <h3>DEVELOPMENT</h3>
            </div>
          </div>

          <div className="">
              <div className="flex items-center justify-center min-h-screen bg-index-bg-m  lg:bg-index-bg bg-cover">
                <div className="text-center"> 
                  <h3 className="font-barcode font-medium text-3xl">HANNAH MCG</h3>

                </div>
              </div>  
          </div>

        </section>

      </main>

    </div>
  )
}