import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillLinkedin, AiFillGithub, AiOutlineMail}  from 'react-icons/ai';
import Image from 'next/image';
import kirby from '../public/kirbyheadphoneblend-crop.png';
import web4 from '../public/glossier.png';
import web2 from '../public/spotifyalbum.png';
import web3 from '../public/gallery.png';
import web1 from '../public/koss.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import stardrawing from '../public/stardrawing.png';
import {useState} from 'react';
import PortTabs from '../components/PortTabs.js';
import Link from 'next/link';


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Hannah McGowan Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className= "bg-white dark:bg-slate-900 px-10 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="pt-10 mb-6 flex justify-between text-slate-900 dark:text-white">
            <Link href="/"><h1 className="text-xl font-pixel">HM:H+M</h1></Link>
            <ul className="flex items-center">
              <li> 
                <BsFillMoonStarsFill 
                onClick={() => setDarkMode(!darkMode)} 
                className="cursor-pointer text-2xl"/>
              </li>
              <li><Link href="/work" className="ml-5 font-semibold">Work</Link></li>
              <li><Link href="/about" className="ml-5 font-semibold">About</Link></li>
              <li><Link href="/gallery" className="ml-5 font-semibold">Gallery</Link></li>
            </ul>
          </nav>
        <div className="mx-auto mt-8 relative h-80 w-auto md:h-90 md:w-90">
          <Image  src={stardrawing} className="object-cover" fill alt="3d kirby with headphones render"/>   
        </div>
        <div className=" lg:flex items-center mt-20" >
          <div className="lg:w-3/5 items-center">
            <div className="text-center p-10">
              <h2 className="text-5xl py-2 text-slate-700 dark:text-slate-300 font-medium md:text-6xl">Hannah McGowan</h2>
              <h3 className="text-2xl py-2 md:text-3xl text-slate-900 dark:text-slate-400">front-end/web developer and designer.</h3>
              <p className="text-md py-5 leading-8 text-slate-500 dark:text-slate-600 md:text-lg max-w-xl mx-auto">Welcome to my website! I'm an aspiring frontend and/or fullstack developer with an emphasis on encapsulating UI/UX design. This is my showcase of past projects and other artworks. Check it out. </p>
            </div>
            <div className="text-5xl flex justify-center gap-16 py-1 text-slate-300  dark:text-slate-600">
              <a href="https://www.linkedin.com/in/hannah-m-74b800120" target="_blank"> <AiFillLinkedin /> </a>
              <a href="https://github.com/hannahmcg" target="_blank">  <AiFillGithub /> </a>
              <a href="mailto:hannahcmcg@berkeley.edu"> <AiOutlineMail /> </a>
            </div> 
          </div>
          <div className="lg:w-2/5 text-center">
            <div className="mx-auto mt-8 relative h-80 w-80 md:h-90 md:w-90">
              <Image src={kirby} className="object-cover" fill alt="3d kirby with headphones render"/>
            </div>
            <p className="mb-20 text-sm text-slate-500 p-5 mx-5">I like trying out new art styles. This is headphones kirby (made in blender).</p>
          </div>
        </div>
        <div>
          <iframe className="rounded-xl" src="https://open.spotify.com/embed/playlist/613PD49YymDxtoW5FMMa4a?utm_source=generator" width="100%" height="352" frameBorder="0" allowFullScreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
        </div>
        </section>

          {/*<div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image src={web1} className="rounded-lg object-cover" 
              width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web2} className="rounded-lg object-cover" 
              width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web3} className="rounded-lg object-cover" 
              width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web4} className="rounded-lg object-cover" 
              width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web5} className="rounded-lg object-cover" 
              width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web6} className="rounded-lg object-cover" 
              width={'100%'} height={'100%'} layout="responsive"/>
            </div>
          </div>*/}

         {/* <div className="">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 flex">
              <div>
              <h3 className="text-lg font-medium pt-8 pb-2">cssa</h3>
              <p className="py-2">creating cool designs according to whichever specs</p>
              <h4 className="py-4 text-blue-400">design tags</h4>
              <p className="text-slate-700 py-1">figma</p>
              <p className="text-slate-700 py-1">illustrator</p>
              <p className="text-slate-700 py-1">photoshop</p>
              </div>
              <Image src={mcgpaint} width={400} height={200} className="mx-auto" />
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 flex bg-slate-50">
              <div>
              <h3 className="text-lg font-medium pt-8 pb-2">mcg painting</h3>
              <p className="py-2">creating cool designs according to whichever specs</p>
              <h4 className="py-4 text-blue-400">design tags</h4>
              <p className="text-slate-700 py-1">figma</p>
              <p className="text-slate-700 py-1">illustrator</p>
              <p className="text-slate-700 py-1">photoshop</p>
              </div>
              <Image src={design} width={100} height={100} className="mx-auto" />
            </div>
  </div> */}
      </main>

    </div>
  )
}
