import Head from 'next/head';
import {useState} from 'react';
import NavMain from '../components/Nav.js';
import { FaArrowDown } from "react-icons/fa";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Hannah McGowan's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/kirbyicon.png" />
      </Head>
      
      <main className= "min-h-screen  bg-gray-50">

      <NavMain />
        <section className="px-5 md:px-8 lg:px-10 pt-20 md:pt-5">

          <div className="pt-20 min-h-screen bg-blue-gray-100 my-4 mt-4 mb-20">
            <h1 className="text-6xl md:text-9xl pl-4">HANNAH MCG</h1>
            <div className="pl-5 md:pl-6">
              <h3>PORTFOLIO</h3>
              <h3>DIGITAL DESIGN</h3>
              <h3>DEVELOPMENT</h3>
            </div>
            <div className="flex">
            <FaArrowDown className="mx-auto"/>
            </div>
          </div>

          <div className="">
              <div className="flex items-center justify-center h-screen bg-index-bg-m  lg:bg-index-bg bg-contain bg-no-repeat bg-center">
                <div className="text-center"> 
                <div>
                  <ul className="flex text-sm space-x-2">
                    <li><a className=" hover:text-light-blue-500" href="HannahMcGowanResume.pdf" target="_blank">RESUME</a></li>
                    <li><a className=" hover:text-light-blue-500" href="https://github.com/hannahmcg" target="_blank">GITHUB</a></li>
                    <li><a className=" hover:text-light-blue-500" href="mailto:hannahcmcg@berkeley.edu">EMAIL</a></li>
                  </ul>
                </div>
                  <h3 className="font-barcode font-medium text-3xl">HANNAH MCG</h3>

                </div>
              </div>  
          </div>

        </section>

      </main>

    </div>
  )
}