import Head from 'next/head';
import Image from 'next/image';
import kirby from '../public/kirbyheadphoneblend-crop.png';
import {useState} from 'react';
import PortTabs from '../components/PortTabs.js';
import Link from 'next/link';
import stickers1 from '../public/index-stickers1.png';
import stickerssm from '../public/index-stickers-sm.png';
import stickerssmM from '../public/index-stickers-smM.png';
import stickers11 from '../public/index-stickers11.png';
import NavMain from '../components/Nav.js';
import meblurry from '../public/me_blurry.jpeg';
import {HiOutlineDocumentText} from 'react-icons/hi';
import {AiFillLinkedin, AiFillGithub, AiOutlineMail}  from 'react-icons/ai';


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Hannah McGowan's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/kirbyicon.png" />
      </Head>

      
      <main className= "min-h-screen  bg-gray-50">

      <NavMain />
        <section className="px-5 md:px-8 lg:px-10 pt-20 md:pt-5">
          <div className="pt-20 min-h-screen bg-blue-gray-100 my-4 mx-4">

            <h1 className="text-9xl pl-3">HANNAH MCG</h1>
            <div className="pl-5">
              <h3>PORTFOLIO</h3>
              <h3>DIGITAL DESIGN</h3>
              <h3>DEVELOPMENT</h3>
            </div>

          </div>




{/*
          <div className="min-h-screen flex items-center justify-center bg-index-bg">
            <div className="text-center"> 
              <h3 className="font-bold">HANNAH MCG</h3>

            </div>


  </div>  */}

        </section>



      </main>


    </div>
  )
}
