import Head from 'next/head';
import Image from 'next/image';
import kirby from '../public/kirbyheadphoneblend-crop.png';
import {useState} from 'react';
import PortTabs from '../components/PortTabs.js';
import Link from 'next/link';
import stickers1 from '../public/index-stickers1.png';
import stickerssm from '../public/index-stickers-sm.png';
import stickerssmM from '../public/index-stickers-smM.png';
import stickers11 from '../public/index-stickers11.png';
import NavMain from '../components/Nav.js';
import meblurry from '../public/me_blurry.jpeg';
import {HiOutlineDocumentText} from 'react-icons/hi';
import {AiFillLinkedin, AiFillGithub, AiOutlineMail}  from 'react-icons/ai';


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Hannah McGowan's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/kirbyicon.png" />
      </Head>

      
      <main className= "min-h-screen  bg-gray-50">

      <NavMain />
        <section className="px-5 md:px-8 lg:px-10 pt-20 md:pt-5">
          <div className="flex justify-center 3xl:pt-10">
            {/*<Image src={stickerstext} className="hidden lg:block" width={1200} height={1200} priority={true} alt="fruit stickers with my info in them"/>*/}
            <Image src={stickerssm} className="hidden lg:block w-full h-auto" sizes="100vw" width="0" height="0" placeholder="blur" priority={true} alt="fruit stickers with my info in them"/>
            <Image src={stickerssmM} className="lg:hidden w-full h-auto" sizes="100vw" width="0" height="0" priority={true} alt="fruit stickers with my info in them"/>
          </div>
        </section>



      </main>


    </div>
  )
}
