import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillLinkedin, AiFillGithub, AiOutlineMail}  from 'react-icons/ai';
import Image from 'next/image';
import kirby from '../public/kirbyheadphoneblend-crop.png';
import web4 from '../public/glossier.png';
import web2 from '../public/spotifyalbum.png';
import web3 from '../public/gallery.png';
import web1 from '../public/koss.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import stardrawing from '../public/stardrawing.png';
import {useState} from 'react';
import PortTabs from '../components/PortTabs.js';
import Link from 'next/link';
import stickers0 from '../public/index-stickers0.png';


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Hannah McGowan Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/kirbyicon.png" />
      </Head>

      <main className= "px-10 md:px-20 lg:px-40">
        <nav className="py-10 max-w-screen-xl flex flex-wrap justify-between mx-auto items-center text-slate-900">
        {/*<nav className="pt-10 md:mb-6 flex justify-between text-slate-900 dark:text-white">*/}
          <Link href="/"><h1 className="text-xl font-pixel">HM:H+M</h1></Link>
          <ul className="flex items-center">
            {/*  <li> 
              <BsFillMoonStarsFill 
              onClick={() => setDarkMode(!darkMode)} 
              className="cursor-pointer text-2xl"/>
            </li>  */}
            <li><Link href="/work" className="ml-8 font-semibold hover:text-light-blue-500 active:text-light-blue-800">Work</Link></li>
            <li><Link href="/about" className="ml-8 font-semibold hover:text-light-blue-500 active:text-light-blue-800">About</Link></li>
            <li><Link href="/gallery" className="ml-8 font-semibold hover:text-light-blue-500 active:text-light-blue-800">Gallery</Link></li>
          </ul>
        </nav>
        {/*<section className="min-h-screen">*/}
        <section className="h-[100%] w-[100%] relative">
            <Image src={stickers0} className="object-cover" responsive alt="fruit stickers with my info in them"/>
        </section>

        {/*}
        <section className="">
        <div className="lg:flex items-center mt-10 md:mt-20" >
          <div className="lg:w-3/5 items-center">
            <div className="text-center p-10">
              <h2 className="text-3xl md:text-6xl py-2 text-slate-700 dark:text-slate-300 font-medium">Hannah McGowan</h2>
              <h3 className="text-lg md:text-3xl py-2 text-slate-900 dark:text-slate-400">full stack developer and designer.</h3>
              <p className="text-sm md:text-lg py-5 leading-8 text-slate-500 dark:text-slate-600 max-w-xl mx-auto">
                Welcome to my website! I'm an aspiring fullstack/frontend developer with an emphasis on encapsulating UI/UX design. 
                This is my showcase of past projects and other artworks. Check it out. </p>
            </div>
          </div>
          <div className="lg:w-2/5 text-center">
            <div className="mx-auto mt-2 md:mt-8 relative h-80 w-80 md:h-90 md:w-90">
              <Image src={kirby} className="object-cover" fill alt="3d kirby with headphones render"/>
            </div>
          </div>
        </div>
          </section> */}


        <div className="mt-10 mb-10">
          {/*}
          <Image src={stardrawing} className="mx-auto" width={400} height={400} alt="3d kirby with headphones render"/>  */}
          <div className="text-5xl flex justify-center gap-16 py-1 text-slate-300  dark:text-slate-600">
              <a href="https://www.linkedin.com/in/hannah-m-74b800120" target="_blank"> <AiFillLinkedin /> </a>
              <a href="https://github.com/hannahmcg" target="_blank">  <AiFillGithub /> </a>
              <a href="mailto:hannahcmcg@berkeley.edu"> <AiOutlineMail /> </a>
          </div>  
        </div>

          {/*<div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image src={web1} className="rounded-lg object-cover" 
              width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web2} className="rounded-lg object-cover" 
              width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web3} className="rounded-lg object-cover" 
              width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web4} className="rounded-lg object-cover" 
              width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web5} className="rounded-lg object-cover" 
              width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web6} className="rounded-lg object-cover" 
              width={'100%'} height={'100%'} layout="responsive"/>
            </div>
          </div>*/}
      </main>

    </div>
  )
}
