import Head from 'next/head';
import Image from 'next/image';
import kirby from '../public/kirbyheadphoneblend-crop.png';
import Link from 'next/link';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import compasscard from '../public/cards/compass-card.png';
import cssacard from '../public/cards/cssa-card.png';
import mcgpaintcard from '../public/cards/mcgpaint-card.png';
import dispotifycard from '../public/cards/dispotify-card.png';
import NavMain from '../components/Nav.js';

function Work() {
    return (
      <div>
          <Head>
              <title>Hannah McGowan Portfolio</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/kirbyicon.png" />
          </Head>
  
          <NavMain />
          <main className="px-10 md:px-20 lg:px-40 pb-20 pt-5">
    
            <div className="text-center pb-10">
                <h1 className="text-4xl pb-5 text-slate-900">work & projects</h1>
                <p className="text-lg text-slate-400">my website’s tech stack: figma, next.js, tailwind, material tailwind</p>
            </div>
              {/*<div className="flex items-center justify-center">
                  <div className="px-2 py-4 text-center">
                      <h1 className="font-semibold">This portfolio's tech stack: next.js, tailwind, material tailwind</h1>
                  </div>
                </div>*/}
              <section>
                <div className="flex flex-col lg:flex-row lg:justify-center lg:gap-10 items-center">
                    <Link href="cards/compass" className="w-[300px] md:w-[400px]">
                        <div className="shadow-lg hover:shadow-2xl hover:shadow-light-blue-100 overflow-hidden dark:shadow-blue-500 rounded-xl my-10 active:border-blue-200 active:border-2">
                            <div className="relative w-full h-80">
                                <Image src={compasscard} className="object-cover" fill alt="compass logo"/>
                            </div>
                            <div className="p-5 mt-4">
                                <h3 className="text-lg font-bold text-slate-900 dark:text-slate-300">COMPASS - C4SF</h3>
                                <p className="py-1 text-slate-800 dark:text-slate-400 text-sm">Develop & Design for Nonprofit Work</p>
                                {/*<p className="text-slate-500  dark:text-slate-400 py-1">Nonprofit app for collecting IEP student data.</p>*/}
                            </div>
                        </div>
                    </Link>
                    <Link href="cards/cssa" className="w-[300px] md:w-[400px]">
                        <div className="shadow-lg hover:shadow-2xl hover:shadow-light-blue-100 overflow-hidden dark:shadow-blue-500 rounded-xl my-10 active:border-blue-200 active:border-2">
                            <div className="relative w-full h-80">
                                <Image src={cssacard} className="object-cover" fill alt="cssa logo"/>
                            </div>
                            <div className="p-5 mt-4">
                                <h3 className="text-lg font-bold text-slate-900 dark:text-slate-300">CSSA WEB REBUILD</h3>
                                <p className="py-1 text-slate-800 dark:text-slate-400 text-sm">Ideate, Plan, Design and Build for my org</p>
                                {/*<p className="text-slate-500  dark:text-slate-400 py-1">Complete website rebuild for Berkeley CSSA.</p>*/}
                            </div>
                        </div>
                    </Link>
                </div>
                <div className="flex flex-col lg:flex-row lg:justify-center lg:gap-10 items-center">
                    <Link href="cards/mcgpaint" className="w-[300px] md:w-[400px]">
                        <div className="shadow-lg hover:shadow-2xl hover:shadow-light-blue-100 overflow-hidden rounded-xl my-10 active:border-blue-200 active:border-2">
                            <div className="relative w-full h-80">
                                <Image src={mcgpaintcard} className="object-cover" fill alt="compass logo"/>
                            </div>
                            <div className="p-5 mt-4">
                                <h3 className="text-lg font-bold text-slate-900 dark:text-slate-300">MCGOWAN PAINTING</h3>
                                <p className="py-1 text-slate-800 dark:text-slate-400">#HTML, CSS, Javascript</p>
                                {/*<p className="text-slate-500  dark:text-slate-400 py-1">Nonprofit app for collecting IEP student data.</p>*/}
                            </div>
                        </div>
                    </Link>
                    <Link href="cards/dispotify" className="w-[300px] md:w-[400px]">
                        <div className="shadow-lg hover:shadow-2xl hover:shadow-light-blue-100 active:border-blue-200 active:border-2 overflow-hidden rounded-xl my-10">
                            <div className="relative w-full h-80">
                                <Image src={dispotifycard} className="object-cover" fill alt="cssa logo"/>
                            </div>
                            <div className="p-5 mt-4">
                                <h3 className="text-lg font-bold text-slate-900 dark:text-slate-300">DISCOVER SPOTIFY</h3>
                                <p className="py-1 text-slate-800 dark:text-slate-400">#Spotify API, Next.js, tailwind</p>
                                {/*<p className="text-slate-500  dark:text-slate-400 py-1">Complete website rebuild for Berkeley CSSA.</p>*/}
                            </div>
                        </div>
                    </Link>
                </div>
              </section>
          </main>
      </div>
    )
  }
  
  export default Work