import Head from 'next/head';
import Image from 'next/image';
import kirby from '../public/kirbyheadphoneblend-crop.png';
import Link from 'next/link';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import compasscard from '../public/cards/compass-card.png';
import cssacard from '../public/cards/cssa-card.png';
import mcgpaintcard from '../public/cards/mcgpaint-card.png';
import dispotifycard from '../public/cards/dispotify-card.png';

function Work() {
    return (
      <div>
          <Head>
              <title>Hannah McGowan Portfolio</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
  
          <nav className="p-10 max-w-screen-xl flex flex-wrap justify-between mx-auto items-center text-slate-900 dark:text-white">
              <Link href="/"><h1 className="text-xl font-pixel">HM:H+M</h1></Link>
              <div className="w-ful md:block md:w-auto">
                <ul className="flex items-center">
                  <li>
                    <BsFillMoonStarsFill 
                    onClick={() => setDarkMode(!darkMode)} 
                    className="cursor-pointer text-2xl"/>
                  </li>
                  <li><Link href="/work" className="ml-5 font-semibold">Work</Link></li>
                  <li><Link href="/about" className="ml-5 font-semibold">About</Link></li>
                  <li><Link href="/gallery" className="ml-5 font-semibold">Gallery</Link></li>
                </ul>
              </div>
          </nav>
  
          <main className="px-20 pb-20 pt-10 w-screen">
              <div className="flex items-center justify-center">
                  <div className="px-2 py-4">
                      <h1 className="font-semibold">This portfolio's tech stack: next.js, tailwind, material tailwind</h1>
                  </div>
              </div>
              <section>
                <div className="lg:flex lg:justify-center gap-10 items-center">
                    <Link href="cards/compass" className="lg:w-1/3">
                        <div className="shadow-lg hover:shadow-2xl overflow-hidden dark:shadow-blue-500 rounded-xl my-10">
                            <div className="relative w-full h-80">
                                <Image src={compasscard} className="object-cover" fill alt="compass logo"/>
                            </div>
                            <div className="p-5 mt-4">
                                <h3 className="text-lg font-bold text-slate-900 dark:text-slate-300">COMPASS - C4SF</h3>
                                <p className="py-1 text-slate-800 dark:text-slate-400">#Next.js, Postgresql, Typescript</p>
                                {/*<p className="text-slate-500  dark:text-slate-400 py-1">Nonprofit app for collecting IEP student data.</p>*/}
                            </div>
                        </div>
                    </Link>
                    <Link href="cards/cssa" className="lg:w-1/3">
                        <div className="shadow-lg hover:shadow-2xl overflow-hidden dark:shadow-blue-500 rounded-xl my-10">
                            <div className="relative h-80 w-full md:h-90">
                                <Image src={cssacard} className="object-cover" fill alt="cssa logo"/>
                            </div>
                            <div className="p-5 mt-4">
                                <h3 className="text-lg font-bold text-slate-900 dark:text-slate-300">CSSA WEB REBUILD</h3>
                                <p className="py-1 text-slate-800 dark:text-slate-400">#HTML, CSS, JS, Github</p>
                                {/*<p className="text-slate-500  dark:text-slate-400 py-1">Complete website rebuild for Berkeley CSSA.</p>*/}
                            </div>
                        </div>
                    </Link>
                </div>
                <div className="lg:flex lg:justify-center gap-10 items-center">
                <Link href="cards/mcgpaint" className="lg:w-1/3">
                    <div className="shadow-lg hover:shadow-2xl overflow-hidden dark:shadow-blue-500 rounded-xl my-10">
                        <div className="relative w-full h-80">
                            <Image src={mcgpaintcard} className="object-cover" fill alt="compass logo"/>
                        </div>
                        <div className="p-5 mt-4">
                            <h3 className="text-lg font-bold text-slate-900 dark:text-slate-300">MCGOWAN PAINTING</h3>
                            <p className="py-1 text-slate-800 dark:text-slate-400">#HTML, CSS, Javascript</p>
                            {/*<p className="text-slate-500  dark:text-slate-400 py-1">Nonprofit app for collecting IEP student data.</p>*/}
                        </div>
                    </div>
                </Link>
                <Link href="cards/dispotify" className="lg:w-1/3">
                    <div className="shadow-lg hover:shadow-2xl active:border-blue-600 border-blue-500 overflow-hidden dark:shadow-blue-500 rounded-xl my-10">
                        <div className="relative h-80 w-full md:h-90">
                            <Image src={dispotifycard} className="object-cover" fill alt="cssa logo"/>
                        </div>
                        <div className="p-5 mt-4">
                            <h3 className="text-lg font-bold text-slate-900 dark:text-slate-300">CSSA WEB REBUILD</h3>
                            <p className="py-1 text-slate-800 dark:text-slate-400">#HTML, CSS, JS, Github</p>
                            {/*<p className="text-slate-500  dark:text-slate-400 py-1">Complete website rebuild for Berkeley CSSA.</p>*/}
                        </div>
                    </div>
                </Link>
                </div>
              </section>
          </main>
      </div>
    )
  }
  
  export default Work