import Head from 'next/head';
import Image from 'next/image';
import kirby from '../public/kirbyheadphoneblend-crop.png';
import Link from 'next/link';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import compasscard from '../public/cards/compass-card.png';
import cssacard from '../public/cards/cssa-card.png';
import mcgpaintcard from '../public/cards/mcgpaint-card.png';
import hbcard from '../public/cards/hb-card.png';
import dispotifycard from '../public/cards/dispotify-card.png';
import NavMain from '../components/Nav.js';

function WorkNew2() {
    return (
      <div>
          <Head>
              <title>Hannah McGowan's Portfolio</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/kirbyicon.png" />
          </Head>
  
          <NavMain />
          <main className="px-10 md:px-20 lg:px-40 pb-20 pt-20 bg-gray-50">
    
            <div className="text-center pb-10">
                <h1 className="text-5xl pb-5 text-slate-900">WORK + PROJECTS</h1>
                <p className="text-base text-slate-500">My Website’s Tech Stack: Figma, Next.js, Tailwind CSS, Material Tailwind</p>
            </div>
              
              <section>
                <div className="grid grid-cols-1 md:grid-cols-2 place-items-center gap-8">
                    <div className="hover:bg-slate-100 py-2 px-4 mx-4">
                        <div className="flex justify-between">
                            <p className="text-xl">COMPASS</p>
                            <div className="text-xs md:text-sm flex">
                                <p className="outline-slate-900 outline-1 outline rounded-md px-3 py-1 w-fit h-fit md:mx-2">full stack development</p>
                                <p className="outline-slate-900 outline-1 outline rounded-md px-3 py-1 w-fit h-fit ml-2 md:mx-2">ui/ux design</p>
                            </div>
                        </div>
                        <div className="mt-5 relative w-full h-60 md:h-80">
                            <Image src={compasscard} className="object-cover" fill alt="compass logo"/>
                        </div>
                        <p className="text-sm">
                            Open-source application built for case managers and paraeducators of the SFUSD.
                            Digitizing their workflow processes, especially in data collection and analysis.
                        </p>
                    </div>

                    <div className="hover:bg-slate-100 py-2 px-4 mx-4 mt-6 md:mt-0">
                        <div className="flex justify-between">
                            <p className="text-xl">HOPS&BEANS</p>
                            <div className="text-xs md:text-sm flex">
                                <p className="outline-slate-900 outline-1 outline rounded-md px-3 py-1 w-fit h-fit md:mx-2">web design + development</p>
                                <p className="outline-slate-900 outline-1 outline rounded-md px-3 py-1 w-fit h-fit ml-2 md:mx-2">ui/ux design</p>
                            </div>
                        </div>
                        <div className="mt-5 relative w-full h-60 md:h-80">
                            <Image src={compasscard} className="object-cover" fill alt="compass logo"/>
                        </div>
                        <p className="text-sm">
                            Website designed and developed for Hops & Beans Cafe, a locally-owned cafe 
                            within a historical building serving craft coffee, beer, and a great selection of foods.
                        </p>
                    </div>
                </div>

                <div className="flex flex-col md:flex-row gap-6 justify-center mt-20 h-96">
                    <div className="hover:bg-slate-100 py-2 px-2 w-96">
                        <div className="flex justify-between">
                            <p className="text-xl">CSSA</p>
                            <div className="text-sm flex">
                                <p className="outline-slate-900 outline-1 outline rounded-md px-3 py-1 w-fit h-fit md:mx-2">web design + development</p>
                                <p className="outline-slate-900 outline-1 outline rounded-md px-3 py-1 w-fit h-fit ml-2 md:mx-2">ui/ux design</p>
                            </div>
                        </div>
                        <div className="mt-5">
                            <Image src={compasscard} priority={true} className="object-contain" width={500} height={500} alt="compass logo"/>
                        </div>
                        <p className="mr-4 text-sm md:pt-4">
                            Website designed, built, and managed for the Cognitive Science Student Association at UC Berkeley;
                            servicing students, faculty, and anyone interested in CogSci.
                        </p>
                    </div>

                    <div className="hover:bg-slate-100 py-2 px-2">
                        <div className="flex justify-between flex-wrap">
                            <p className="text-xl">DISCOVERSPOTIFY</p>
                            <div className="text-sm flex">
                                <p className="outline-slate-900 outline-1 outline rounded-md px-3 py-1 w-fit h-fit md:mx-2">full stack development</p>
                                <p className="outline-slate-900 outline-1 outline rounded-md px-3 py-1 w-fit h-fit ml-2 md:mx-2">ui design</p>
                            </div>
                        </div>
                        <div className="mt-5">
                            <Image src={compasscard} priority={true} className="object-contain" width={500} height={500} alt="compass logo"/>
                        </div>
                        <p>Description</p>
                    </div>
                </div>
                
              </section>
          </main>
      </div>
    )
  }
  
  export default WorkNew2