import Head from 'next/head';
import Image from 'next/image';
import kirby from '../public/kirbyheadphoneblend-crop.png';
import Link from 'next/link';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import compasscard from '../public/cards/compass-card.png';
import cssacard from '../public/cards/cssa-card.png';
import mcgpaintcard from '../public/cards/mcgpaint-card.png';
import hbcard from '../public/cards/hb-card.png';
import dispotifycard from '../public/cards/dispotify-card.png';
import NavMain from '../components/Nav.js';

function WorkNew2() {
    return (
      <div>
          <Head>
              <title>Hannah McGowan's Portfolio</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/kirbyicon.png" />
          </Head>
  
          <NavMain />
          <main className="px-10 md:px-20 lg:px-40 pb-20 pt-20 bg-gray-50">
    
            <div className="text-center pb-10">
                <h1 className="text-5xl pb-5 text-slate-900">WORK + PROJECTS</h1>
                <p className="text-base text-slate-500">My Website’s Tech Stack: Figma, Next.js, Tailwind CSS, Material Tailwind</p>
            </div>
              
              <section>
                <div className="grid grid-cols-2">
                    <div className="">
                        <div className="flex">
                            <p>Compass</p>
                            <div className="text-sm flex">
                                <p className="outline-slate-900 outline-1 outline rounded-md px-3 py-1 w-fit h-fit md:mx-2">full stack development</p>
                                <p className="outline-slate-900 outline-1 outline rounded-md px-3 py-1 w-fit h-fit ml-2 md:mx-2">ui/ux design</p>
                            </div>
                        </div>
                        <div className="">
                            <Image src={compasscard} priority={true} className="object-contain" width={400} height={400} alt="compass logo"/>
                        </div>
                        <p>Description</p>
                    </div>
                    <div>
                    <div className="flex">
                            <p>Hops & Beans</p>
                            <div className="text-sm flex">
                                <p className="outline-slate-900 outline-1 outline rounded-md px-3 py-1 w-fit h-fit md:mx-2">full stack development</p>
                                <p className="outline-slate-900 outline-1 outline rounded-md px-3 py-1 w-fit h-fit ml-2 md:mx-2">ui/ux design</p>
                            </div>
                        </div>
                        <div className="">
                            <Image src={compasscard} priority={true} className="object-contain" width={400} height={400} alt="compass logo"/>
                        </div>
                        <p>Description</p>

                    </div>
                </div>
                <div>
                    <div>
                        <p>CSSA</p>

                    </div>
                    <div>
                        <p>DiscoverSpotify</p>

                    </div>
                </div>
                
               

                
                
              </section>
          </main>
      </div>
    )
  }
  
  export default WorkNew2