import Head from 'next/head';
import Image from 'next/image';
import kirby from '../public/kirbyheadphoneblend-crop.png';
import Link from 'next/link';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import compasscard from '../public/cards/compass-card.png';
import cssacard from '../public/cards/cssa-card.png';
import mcgpaintcard from '../public/cards/mcgpaint-card.png';
import hbcard from '../public/cards/hb-card.png';
import dispotifycard from '../public/cards/dispotify-card.png';
import NavMain from '../components/Nav.js';

function Work() {
    return (
      <div>
          <Head>
              <title>Hannah McGowan's Portfolio</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/kirbyicon.png" />
          </Head>
  
          <NavMain />
          <main className="px-10 md:px-20 lg:px-40 pb-20 pt-20 bg-gray-50">
    
            <div className="text-center pb-10">
                <h1 className="text-4xl pb-5 text-slate-900">WORK + PROJECTS</h1>
                <p className="text-lg text-slate-400">My Website’s Tech Stack: Next.js, Tailwind CSS, Material Tailwind</p>
            </div>
              {/*<div className="flex items-center justify-center">
                  <div className="px-2 py-4 text-center">
                      <h1 className="font-semibold">This portfolio's tech stack: next.js, tailwind, material tailwind</h1>
                  </div>
                </div>*/}
              <section className="">
                <div className="flex flex-col lg:flex-row lg:justify-center lg:gap-10 items-center">
                    <Link href="cards/compass" className="w-[300px] md:w-[400px] h-[600px]">
                        <div className="shadow-lg hover:shadow-2xl hover:shadow-light-blue-100 hover:border-slate-200 hover:border-2 overflow-hidden dark:shadow-blue-500 rounded-xl my-10 active:border-blue-200 active:border-2">
                            <div className="relative w-full h-40 md:h-60">
                                <Image src={compasscard} className="object-cover" fill alt="compass logo"/>
                            </div>
                            <div className="p-5 mt-2">
                                <h3 className="text-2xl text-slate-900">COMPASS</h3>
                                <p className="text-slate-900 text-sm mt-2 py-1">
                                    Open-source application built for case managers and paraeducators of the SFUSD. 
                                    Digitizing their workflow processes, especially in data collection and analysis.
                                </p>
                                <div className="flex text-sm mt-4 text-slate-500">
                                    <p className="outline-slate-400 outline-1 outline rounded-md px-2 py-1 w-fit h-fit">full stack development</p>
                                    <p className="outline-slate-400 outline-1 outline rounded-md px-2 py-1 w-fit h-fit ml-2">ui/ux design</p>
                                </div>
                                <p className="text-sm mt-2 py-1 text-slate-500">#Next.js, Typescript, PostgreSQL, Figma</p>
                                {/*<p className="text-slate-500  dark:text-slate-400 py-1">Nonprofit app for collecting IEP student data.</p>*/}
                            </div>
                        </div>
                    </Link>
                    <Link href="cards/cssa" className="w-[300px] md:w-[400px] h-[600px]">
                        <div className="shadow-lg hover:shadow-2xl hover:shadow-light-blue-100 hover:border-slate-200 hover:border-2 overflow-hidden dark:shadow-blue-500 rounded-xl my-10 active:border-blue-200 active:border-2">
                            <div className="relative w-full h-40 md:h-60">
                                <Image src={cssacard} className="object-cover" fill alt="cssa logo"/>
                            </div>
                            <div className="p-5 mt-2">
                                <h3 className="text-2xl text-slate-900">CSSA</h3>
                                <p className="text-slate-900 text-sm mt-2 py-1">
                                    Website designed, built, and managed for the Cognitive Science Student Association at UC Berkeley;
                                    servicing students, faculty, and anyone interested in CogSci.
                                </p>
                                <div className="flex text-sm mt-4 text-slate-600">
                                    <p className="outline-slate-400 outline-1 outline rounded-md px-2 py-1 w-fit h-fit">web design + development</p>
                                    <p className="outline-slate-400 outline-1 outline rounded-md px-2 py-1 w-fit h-fit ml-2">ui/ux design</p>
                                </div>
                                <p className="text-sm mt-2 py-1 text-slate-600">#HTML, CSS, Javascript, Figma, OCF</p>
                            </div>
                        </div>
                    </Link>
                </div>
                <div className="flex flex-col lg:flex-row lg:justify-center lg:gap-10 items-center pb-10">
                    <Link href="cards/hopsandbeans" className="ww-[300px] md:w-[400px] h-[600px]">
                        <div className="shadow-lg hover:shadow-2xl hover:shadow-light-blue-100 overflow-hidden rounded-xl my-10 active:border-blue-200 active:border-2">
                            <div className="relative w-full h-40 md:h-60">
                                <Image src={hbcard} className="object-cover" fill alt="Hops & Beans Cafe Logo"/>
                            </div>
                            <div className="p-5 mt-2">
                                <h3 className="text-2xl text-slate-900">HOPS & BEANS</h3>
                                <p className="text-slate-900 text-sm mt-2 py-1">
                                Website designed and developed for Hops & Beans Cafe, a locally-owned cafe 
                                within a historical building serving craft coffee, beer, and a great selection of foods.
                                </p>
                                <div className="flex text-sm mt-4 text-slate-600">
                                    <p className="outline-slate-400 outline-1 outline rounded-md px-2 py-1 w-fit h-fit">web design + development</p>
                                    <p className="outline-slate-400 outline-1 outline rounded-md px-2 py-1 w-fit h-fit ml-2">ui/ux design</p>
                                </div>
                                <p className="text-sm mt-2 py-1 text-slate-600">#Wordpress, Elementor, Figma, Figjam</p>
                            </div>
                        </div>
                    </Link>
                    <Link href="cards/dispotify" className="w-[300px] md:w-[400px] h-[600px]">
                        <div className="shadow-lg hover:shadow-2xl hover:shadow-light-blue-100 active:border-blue-200 active:border-2 overflow-hidden rounded-xl my-10">
                            <div className="relative w-full h-40 md:h-60">
                                <Image src={dispotifycard} className="object-cover" fill alt="Discover Spotify Logo"/>
                            </div>
                            <div className="p-5 mt-2">
                                <h3 className="text-2xl text-slate-900">DISCOVER SPOTIFY</h3>
                                <p className="text-slate-900 text-sm mt-2 py-1">
                                    Website designed, built, and managed for the Cognitive Science Student Association at UC Berkeley;
                                    servicing students, faculty, and anyone interested in CogSci.
                                </p>
                                <div className="flex text-sm mt-4 text-slate-600">
                                    <p className="outline-slate-400 outline-1 outline rounded-md px-2 py-1 w-fit h-fit">web design + development</p>
                                    <p className="outline-slate-400 outline-1 outline rounded-md px-2 py-1 w-fit h-fit ml-2">ui/ux design</p>
                                </div>
                                <p className="text-sm mt-2 py-1 text-slate-600">#Next.js, Typescript, Tailwind CSS, Spotify API</p>
                            </div>
                        </div>
                    </Link>
                </div>
              </section>
          </main>
      </div>
    )
  }
  
  export default Work