import Head from 'next/head';
import Image from 'next/image';
import kirby from '../public/kirbyheadphoneblend-crop.png';
import Link from 'next/link'

function Work() {
  return (
    <div className="p-10 w-screen" >
        <Head>
            <title>Hannah McGowan Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Link href="/" className="text-center">Home</Link>

        <div className="flex items-center justify-center">
            <div className="px-2">
                <h1>About Me</h1>
                <p>Hi I'm hannah. I like things and things and I'm interested in things and I like a lot of things.</p>
                <p>This where i went to school and what I studied. This is cool stuff I do and like to do as hobbies or interests.</p>
            </div>
            <div className="relative h-80 w-80 md:h-90 md:w-90">
            <Image src={kirby} className="object-cover" fill alt="3d kirby with headphones render"/>
            </div>
        </div>
    </div>
  )
}

export default Work