import Head from 'next/head';
import Image from 'next/image';
import kirby from '../public/kirbyheadphoneblend-crop.png';
import Link from 'next/link';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import compasscard from '../public/cards/compass-card.png';
import cssacard from '../public/cards/cssa-card.png';

function Work() {
    return (
      <div>
          <Head>
              <title>Hannah McGowan Portfolio</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
  
          <nav className="p-10 max-w-screen-xl flex flex-wrap justify-between mx-auto items-center text-slate-900 dark:text-white">
              <h1 className="text-xl font-pixel text-cyan-800">HM:H+M</h1>
              <div className="w-ful md:block md:w-auto">
                <ul className="flex items-center">
                  <li>
                    <BsFillMoonStarsFill 
                    onClick={() => setDarkMode(!darkMode)} 
                    className="cursor-pointer text-2xl"/>
                  </li>
                  <li><Link href="/" className="ml-5">Home</Link></li>
                  <li><Link href="/about" className="ml-5">About</Link></li>
                  <li><Link href="/work" className="ml-5">Work</Link></li>
                </ul>
              </div>
          </nav>
  
          <main className="p-20 w-screen">
              <div className="flex items-center justify-center">
                  <div className="px-2">
                      <h1>This portfolio's tech stack: next.js, tailwind, material tailwind</h1>
                  </div>
                  <div className="relative h-80 w-80 md:h-90 md:w-90">
                  <Image src={kirby} className="object-cover" fill alt="3d kirby with headphones render"/>
                  </div>
              </div>
              <section>
                <div className="lg:flex gap-10 items-center">
                    <div className="md:max-w-150 text-center shadow-lg overflow-hidden dark:shadow-blue-500 rounded-xl my-10">
                        <div className="relative w-full h-80">
                            <Image src={compasscard} className="object-cover" fill alt="compass logo"/>
                        </div>
                        <h3 className="text-lg font-medium pt-8 pb-2 text-slate-900 dark:text-slate-300">COMPASS - C4SF</h3>
                        <p className="py-2 text-slate-800 dark:text-slate-400">#Next.js, Postgresql, Typescript</p>
                        <p className="text-slate-500  dark:text-slate-400 py-1">Nonprofit app for collecting IEP student data.</p>
                    </div>
                    <div className="md:max-w-150 text-center shadow-lg overflow-hidden dark:shadow-blue-500 rounded-xl my-10">
                        <div className="relative h-80 w-full md:h-90">
                            <Image src={cssacard} className="object-cover" fill alt="cssa logo"/>
                        </div>
                        <h3 className="text-lg font-medium pt-8 pb-2 text-slate-900 dark:text-slate-300">CSSA WEB REBUILD</h3>
                        <p className="py-2 text-slate-800 dark:text-slate-400">#HTML, CSS, JS, Github</p>
                        <p className="text-slate-500  dark:text-slate-400 py-1">Complete website rebuild for Berkeley CSSA.</p>
                    </div>
                </div>
              </section>
          </main>
      </div>
    )
  }
  
  export default Work