import Head from 'next/head';
import Image from 'next/image';
import kirby from '../public/kirbyheadphoneblend-crop.png';
import Link from 'next/link';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import compasscard from '../public/cards/compass-card.png';
import cssacard from '../public/cards/cssa-card.png';
import mcgpaintcard from '../public/cards/mcgpaint-card.png';
import hbcard from '../public/cards/hb-card.png';
import dispotifycard from '../public/cards/dispotify-card.png';
import NavMain from '../components/Nav.js';

function WorkNew() {
    return (
      <div>
          <Head>
              <title>Hannah McGowan's Portfolio</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/kirbyicon.png" />
          </Head>
  
          <NavMain />
          <main className="px-10 md:px-20 lg:px-40 pb-20 pt-20 bg-gray-50">
    
            <div className="text-center pb-10">
                <h1 className="text-5xl pb-5 text-slate-900">WORK + PROJECTS</h1>
                <p className="text-base text-slate-500">My Website’s Tech Stack: Figma, Next.js, Tailwind CSS, Material Tailwind</p>
            </div>
              
              <section>
                <div className="flex">
                    <div className="outline-slate-900 outline-1 outline rounded-md mx-auto grid  grid-cols-1 md:grid-cols-3 h-auto w-full  hover:shadow-lg hover:shadow-light-blue-100 py-6 px-6">
                        <div className="">
                            <p className="text-2xl pb-4">COMPASS</p>
                            <p className="mr-4 text-sm md:pt-4 hidden md:block">Open-source application built for case managers and paraeducators of the SFUSD. Digitizing their workflow processes, especially in data collection and analysis.</p>
                        </div>
                        <div className="">
                            <div className="flex md:justify-end mt-4 md:mt-0 text-sm">
                            <p className="outline-slate-900 outline-1 outline rounded-md px-3 py-1 w-fit h-fit md:mx-2">full stack development</p>
                            <p className="outline-slate-900 outline-1 outline rounded-md px-3 py-1 w-fit h-fit ml-2 md:mx-2">ui/ux design</p>
                            </div>
                            <div className="flex md:justify-end mt-4 md:mt-0">
                                <p className="md:mt-20 text-sm">Next.js, PostgreSQL, Figma, Github projects</p>
                            </div>
                            
                        </div>
                        <div className="hidden md:block">
                        <div className="flex justify-center md:justify-end mt-4 md:mt-0">
                            <Image src={compasscard} priority={true} className="object-contain" width={220} height={200} alt="compass logo"/>
                        </div>
                        </div>
                    </div>
                </div>

                <div className="flex mt-10">
                    <div className="outline-slate-900 outline-1 outline rounded-md mx-auto grid  grid-cols-1 md:grid-cols-3 h-auto w-full hover:bg-slate-100 hover:shadow-xl hover:shadow-light-blue-100 py-6 px-6">
                        <div className="">
                            <div className="flex justify-between">
                                <p className="text-2xl pb-4">COMPASS</p>
                                <div className="md:hidden">
                                    <Image src={compasscard} priority={true} className=" rounded-full" width={50} height={50} alt="compass logo"/>
                                </div>
                            </div>
                            <p className="mr-4 text-sm md:pt-4">Open-source application built for case managers and paraeducators of the SFUSD. Digitizing their workflow processes, especially in data collection and analysis.</p>
                        </div>
                        <div className="">
                            <div className="flex md:justify-end mt-4 md:mt-0 text-sm">
                            <p className="outline-slate-900 outline-1 outline rounded-md px-3 py-1 w-fit h-fit md:mx-2">full stack development</p>
                            <p className="outline-slate-900 outline-1 outline rounded-md px-3 py-1 w-fit h-fit ml-2 md:mx-2">ui/ux design</p>
                            </div>
                            <div className="flex md:justify-end mt-4 md:mt-0">
                                <p className="md:mt-20 text-sm">Next.js, PostgreSQL, Figma, Github projects</p>
                            </div>
                            
                        </div>
                        <div className="hidden md:block">
                        <div className="flex justify-center md:justify-end mt-4 md:mt-0">
                            <Image src={compasscard} priority={true} className="object-contain" width={220} height={200} alt="compass logo"/>
                        </div>
                        </div>
                    </div>
                </div>

                <div className="flex mt-10">
                    <div className="outline-slate-900 outline-1 outline rounded-md mx-auto grid  grid-cols-1 md:grid-cols-3 h-auto w-full hover:bg-slate-200 hover:shadow-xl hover:shadow-light-blue-100 py-6 px-6">
                        <div className="">
                            <p className="text-2xl pb-4">COMPASS</p>
                            <p className="mr-4 text-sm md:pt-4">Open-source application built for case managers and paraeducators of the SFUSD. Digitizing their workflow processes, especially in data collection and analysis.</p>
                        </div>
                        <div className="">
                            <div className="flex md:justify-end mt-4 md:mt-0 text-sm">
                            <p className="outline-slate-900 outline-1 outline rounded-md px-3 py-1 w-fit h-fit md:mx-2">full stack development</p>
                            <p className="outline-slate-900 outline-1 outline rounded-md px-3 py-1 w-fit h-fit ml-2 md:mx-2">ui/ux design</p>
                            </div>
                            <div className="flex md:justify-end mt-4 md:mt-0">
                                <p className="md:mt-20 text-sm">Next.js, PostgreSQL, Figma, Github projects</p>
                            </div>
                            
                        </div>
                        <div className="flex justify-center md:justify-end mt-4 md:mt-0">
                            <Image src={compasscard} priority={true} className="object-contain" width={220} height={200} alt="compass logo"/>
                        </div>
                    </div>
                </div>

                <div className="flex mt-10">
                    <div className="outline-slate-900 outline-1 outline rounded-md mx-auto grid  grid-cols-1 md:grid-cols-3 h-auto w-full hover:bg-slate-200 hover:drop-shadow-md py-6 px-6">
                        <div className="">
                            <p className="text-2xl pb-4">COMPASS</p>
                            <p className="mr-4 text-sm md:pt-4">Open-source application built for case managers and paraeducators of the SFUSD. Digitizing their workflow processes, especially in data collection and analysis.</p>
                        </div>
                        <div className="">
                            <div className="flex md:justify-end mt-4 md:mt-0 text-sm">
                            <p className="outline-slate-900 outline-1 outline rounded-md px-3 py-1 w-fit h-fit md:mx-2">full stack development</p>
                            <p className="outline-slate-900 outline-1 outline rounded-md px-3 py-1 w-fit h-fit ml-2 md:mx-2">ui/ux design</p>
                            </div>
                            <div className="flex md:justify-end mt-4 md:mt-0">
                                <p className="md:mt-20 text-sm">Next.js, PostgreSQL, Figma, Github projects</p>
                            </div>
                            
                        </div>
                        <div className="flex justify-center md:justify-end mt-4 md:mt-0">
                            <Image src={compasscard} priority={true} className="object-contain" width={220} height={200} alt="compass logo"/>
                        </div>
                    </div>
                </div>

                
               

                
                
              </section>
          </main>
      </div>
    )
  }
  
  export default WorkNew