import Head from 'next/head';
import Image from 'next/image';
import kirby from '../public/kirbyheadphoneblend-crop.png';
import Link from 'next/link';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import compasscard from '../public/cards/compass-card.png';
import cssacard from '../public/cards/cssa-card.png';
import mcgpaintcard from '../public/cards/mcgpaint-card.png';
import hbcard from '../public/cards/hb-card.png';
import dispotifycard from '../public/cards/dispotify-card.png';
import NavMain from '../components/Nav.js';

function Work() {
    return (
      <div>
          <Head>
              <title>Hannah McGowan's Portfolio</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/kirbyicon.png" />
          </Head>
  
          <NavMain />
          <main className="px-10 md:px-20 lg:px-40 pb-20 pt-20 bg-gray-50">
    
            <div className="text-center pb-10">
                <h1 className="text-4xl pb-5 text-slate-900">WORK + PROJECTS</h1>
                <p className="text-lg text-slate-400">My website’s tech stack: figma, Next.js, tailwind, material tailwind</p>
            </div>
              
              <section>
                <div className=" outline-slate-900">
                    <div className="grid-cols-3">
                        <div className="">
                            <p></p>
                        </div>
                        <div className="">
                            <p></p>
                        </div>
                        <div className="">
                            <p></p>
                        </div>

                    </div>

                </div>
                
              </section>
          </main>
      </div>
    )
  }
  
  export default Work