import Head from 'next/head';
import Image from 'next/image';
import kirby from '../public/kirbyheadphoneblend-crop.png';
import Link from 'next/link';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import compasscard from '../public/cards/compass-card.png';
import cssacard from '../public/cards/cssa-card.png';
import mcgpaintcard from '../public/cards/mcgpaint-card.png';
import hbcard from '../public/cards/hb-card.png';
import dispotifycard from '../public/cards/dispotify-card.png';
import NavMain from '../components/Nav.js';

function WorkNew() {
    return (
      <div>
          <Head>
              <title>Hannah McGowan's Portfolio</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/kirbyicon.png" />
          </Head>
  
          <NavMain />
          <main className="px-10 md:px-20 lg:px-40 pb-20 pt-20 bg-gray-50">
    
            <div className="text-center pb-10">
                <h1 className="text-4xl pb-5 text-slate-900">WORK + PROJECTS</h1>
                <p className="text-lg text-slate-400">My website’s tech stack: figma, Next.js, tailwind, material tailwind</p>
            </div>
              
              <section>
                <div className="flex">
                    <div className="outline-slate-500 outline rounded-md mx-auto grid grid-cols-3 h-40 w-full hover:bg-light-blue-50">
                        <div className="">
                            <p>COMPASS</p>
                        </div>
                        <div className="">
                            <p className="outline-slate-500 outline rounded-md">full stack development</p>
                            <p>ui/ux design</p>
                        </div>
                        <div className="flex">
                            <Image src={compasscard} priority={true} className="object-contain items-center mx-auto" width={200} height={200} alt="compass logo"/>
                        </div>
                    </div>
                </div>

                <div className="flex mt-10">
                    <div className="outline-slate-500 outline rounded-md mx-auto grid grid-cols-3 h-40 w-full hover:bg-light-blue-50">
                        <div className="">
                            <p>COMPASS</p>
                        </div>
                        <div className="">
                            <p>full stack development</p>
                            <p>ui/ux design</p>
                        </div>
                        <div className="flex">
                            <Image src={compasscard} priority={true} className="object-contain items-center" width={200} height={200} alt="compass logo"/>
                        </div>
                    </div>
                </div>
                
              </section>
          </main>
      </div>
    )
  }
  
  export default WorkNew