import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import compasscomputer from '../../public/cards/compass-computer.png';

function Compass() {
    return (
      <div>
          <Head>
              <title>Hannah McGowan Portfolio</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
  
          <nav className="p-10 max-w-screen-xl flex flex-wrap justify-between mx-auto items-center text-slate-900 dark:text-white">
              <h1 className="text-xl font-pixel text-cyan-800">HM:H+M</h1>
              <div className="w-ful md:block md:w-auto">
                <ul className="flex items-center">
                  <li>
                    <BsFillMoonStarsFill 
                    onClick={() => setDarkMode(!darkMode)} 
                    className="cursor-pointer text-2xl"/>
                  </li>
                  <li><Link href="/" className="ml-5 font-semibold">Home</Link></li>
                  <li><Link href="/work" className="ml-5 font-semibold">Work</Link></li>
                  <li><Link href="/about" className="ml-5 font-semibold">About</Link></li>
                </ul>
              </div>
          </nav>
  
          <main className="px-20 pb-20 pt-10 w-screen">
              <div className="flex flex-col justify-center items-center">
                  <div className="px-2 py-4">
                      <h1 className="font-semibold">Compass Case Study</h1>
                  </div>
                  <section>
                    <div className="relative w-80 h-80">
                        <Image src={compasscomputer} className="object-cover" fill alt="example UI of compass app"/>
                    </div>
              </section>
              </div>
          </main>
      </div>
    )
  }
  
  export default Compass