import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import compasscomputer from '../../public/cards/compass-computer.png';

function Compass() {
    return (
      <div>
          <Head>
              <title>Hannah McGowan Portfolio</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
  
          <nav className="p-10 max-w-screen-xl flex flex-wrap justify-between mx-auto items-center text-slate-900 dark:text-white">
              <h1 className="text-xl font-pixel text-cyan-800">HM:H+M</h1>
              <div className="w-ful md:block md:w-auto">
                <ul className="flex items-center">
                  <li>
                    <BsFillMoonStarsFill 
                    onClick={() => setDarkMode(!darkMode)} 
                    className="cursor-pointer text-2xl"/>
                  </li>
                  <li><Link href="/" className="ml-5 font-semibold">Home</Link></li>
                  <li><Link href="/work" className="ml-5 font-semibold">Work</Link></li>
                  <li><Link href="/about" className="ml-5 font-semibold">About</Link></li>
                </ul>
              </div>
          </nav>
  
          <main className="px-20 pb-20 pt-10 w-screen">
              <section className="items-center text-center min-h-screen">
                <div className="pt-5 pb-10">
                    <Image src={compasscomputer} className="object-contain mx-auto" width={650} height={650} alt="example UI of compass app"/>
                </div>
                <div className="px-2 py-4">
                    <h1 className="font-semibold text-3xl">Project Compass with Code for San Francisco</h1>
                    <p className="text-slate-400 text-sm mt-10">An overview of my involvement with Compass - a nonprofit and volunteer driven project founded within Code for San Francisco.</p>
                </div>
              </section>
              <div className="h-screen motion-safe:animate-fadeIn">
                <h2>This is a title about something</h2>
                <p>more writing and stuff yeah yeah yeah yeah</p>
              </div>
              {/* breaks up rest of case study between nav and information */}
              <section className="flex justify-around">
                <div>
                    <ul className="list-none">
                        <p>Nav</p>
                        <li>Overview</li>
                        <li>About</li>
                    </ul>
                </div>
                <div>
                    {/* first screen: overview */}
                    <div className="h-screen motion-safe:animate-fadeIn">
                        <div className="flex">
                            <div>
                                <p>Role</p>
                                <p>Full Stack Engineer</p>
                            </div>
                            <div>
                                <p>Timeline</p>
                                <p>January-Now</p>
                            </div>
                            <div>
                                <p>Team</p>
                                <p>Compass</p>
                            </div>
                            <div>
                                <p>Something</p>
                                <p>Description</p>
                            </div>
                        </div>
                        <div>
                            <p>Overview</p>
                            <p>Lorem ipsum yadaydaydyadydyyaydayyayd</p>
                        </div>
                    </div>
                </div>
              </section>
          </main>
      </div>
    )
  }
  
  export default Compass