import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import compasscomputer from '../../public/cards/compass-computer.png';
import WorkNav from '../../components/WorkNav';

function Compass() {
    return (
      <div>
          <Head>
              <title>Hannah McGowan Portfolio</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
  
          <nav className="p-10 max-w-screen-xl flex flex-wrap justify-between mx-auto items-center text-slate-900 dark:text-white">
            <Link href="/"><h1 className="text-xl font-pixel">HM:H+M</h1></Link>
            <div className="w-ful md:block md:w-auto">
              <ul className="flex items-center">
                <li>
                  <BsFillMoonStarsFill 
                  onClick={() => setDarkMode(!darkMode)} 
                  className="cursor-pointer text-2xl"/>
                </li>
                <li><Link href="/work" className="ml-5 font-semibold">Work</Link></li>
                <li><Link href="/about" className="ml-5 font-semibold">About</Link></li>
                <li><Link href="/gallery" className="ml-5 font-semibold">Gallery</Link></li>
              </ul>
            </div>
          </nav>
  
          <main className="px-10 md:px-20 lg:px-40 pb-20 pt-10 w-screen">
              <section className="items-center text-center min-h-screen">
                <div className="pt-5 pb-10">
                    <Image src={compasscomputer} className="object-contain mx-auto" width={650} height={650} alt="example UI of compass app"/>
                </div>
                <div className="px-2 py-4">
                    <h1 className="font-semibold text-4xl text-slate-900">Project Compass with Code for San Francisco</h1>
                    <p className="text-slate-400 text-sm mt-10">An overview of my involvement with Compass - a nonprofit and volunteer driven project founded within Code for San Francisco.</p>
                </div>
              </section>
              {/* breaks up rest of case study between nav and information */}
              <section className="flex">
                {/*<div className="">
                    <ul className="list-none">
                        <p>Nav</p>
                        <li>Overview</li>
                        <li>About</li>
                    </ul>
                </div>*/}
                <WorkNav />
                <div className="flex-grow scroll-smooth">
                    {/* first screen: overview 
                    className="pl-10 h-screen motion-safe:animate-fadeIn"*/}
                    <div id="1" className="pl-10 h-screen motion-safe:animate-fadeIn">
                        <div className="w-full flex justify-between text-sm">
                            <div className="text-slate-500 font-light">
                                <p className="font-semibold text-slate-900">Role</p>
                                <p className="">Full Stack Engineer</p>
                            </div>
                            <div className="text-slate-500 font-light">
                                <p className="font-semibold text-slate-900">Timeline</p>
                                <p>Jan 2023 - Current</p>
                            </div>
                            <div className="text-slate-500 font-light">
                                <p className="font-semibold text-slate-900">Team</p>
                                <p>Compass</p>
                            </div>
                            <div className="text-slate-500 font-light">
                                <p className="font-semibold text-slate-900">Tools</p>
                                <p>Next.js, Postgresql, Typescript, tailwindcss</p>
                            </div>
                        </div>
                        <div className="mt-20 text-slate-500 font-light">
                            <p className="font-semibold text-slate-900 pb-1">What is Compass?</p>
                            <p>Compass is a nonprofit and entirely volunteer-led and sustained project 
                                founded within the volunteer brigade, <span className="italic">Code for San Francisco</span>.
                                The project was started with the goal of aiding staff within the SFUSD whose
                                work are focused on students with disabilities, namely case managers and para professionals. The 
                                application aims to streamline their current "nondigital" process of data collection on 
                                what is referred to as a student's IEP - Individual Education Plan. In other words, it 
                                would allow staff to have an easier time keeping track of their students' progress.</p>
                            <br></br>
                            <p>The team is primarily broken up into two subteams - Engineering and Design, although
                                most members (myself included) are simultaneously involved in specific design aspects.
                                The project is still currently in the design phase, although the engineering team has 
                                begun to set up much of the application's building blocks. The initial MVP is scheduled
                                for the beginning of the summer school semester (early June). Check out our github 
                                <a class="text-light-blue-700 hover:text-light-blue-900 cursor-pointer" 
                                href="https://github.com/sfbrigade/compass"> here</a>.
                            </p>
                        </div>
                        <div className="mt-20 text-slate-500 font-light">
                            <p className="font-semibold text-slate-900 pb-1">How am I involved?</p>
                            <p>I joined the project as a full stack engineer with an added interest in product design and UI design. I was looking to broaden
                                my understanding of overall web architecture and knowing the best approaches and methods to take for 
                                a desired product, which I'll get into more detail about below. I've gotten the added benefit of 
                                learning from and working with some incredibly talented people, and I couldn't be more grateful to this 
                                project for giving me the space to make meaningful contributions and grow through creating :D
                            </p>
                        </div>
                    </div>
                    <div id="2" className="pl-10 pt-10 h-screen">
                        <h2 className="text-2xl text-light-blue-800">ABOUT</h2>
                        <div className="mb-20">
                            <div className="mt-10 text-slate-500 font-light">
                                <p className="font-semibold text-slate-900 pb-1">Approaching from an engineering perspective</p>
                                <ul className="list-disc">
                                    <li>start with detailed look at the schema - what users do we needed, what tables might we need, 
                                        what kind of authorization or authentication are we looking at, etc. </li>
                                    <li>more detailed look at approaches we've taken / things we've incorporated into the project
                                        - NextAuth, trpc, docker desktop for postgres database </li>
                                    <li>had a lot of discussions on the usage of relational databases and where they're needed</li>
                                </ul>
                            </div>
                        </div>
                        <div className="">
                            <div className="mt-10 text-slate-500 font-light">
                                <p className="font-semibold text-slate-900 pb-1">Approaching from a design perspective</p>
                                <ul className="list-disc">
                                    <li>design team focused on design system and using those main factors as a guide - 
                                        typography, components, color scheme, logo, etc.</li>
                                    <li>user workflows broken up into more subteams based on the different users interacting with the app. 
                                        The app is geared toward list management for case managers, who assign / delegate tasks to paraprofessionals. 
                                        Thus the application consists of two different faces with varying functionalities, and completely different workflows. 
                                        There’s also a third subteam dedicated toward designing the aspect of data collection and visualization - 
                                        why it’s needed and how it will be displayed in the most useful and efficient way.</li>
                                </ul>
                            </div>
                            {/*<div className="bg-light-blue-400 w-40 h-20 mx-auto mt-5 rounded-xl shadow-lg">
                                <p>hi this is text</p>
                            </div>*/}
                        </div>
                    </div>
                    <div id="3" className="pl-10 pt-10 pb-20">
                        <h2 className="text-2xl text-light-blue-800">MORE</h2>
                        <p className="font-semibold mt-10">Check back here for screencaps of our finalized designs and initial deployed app!</p>
                    </div>
                    <div id="4" className="pl-10 pt-10 pb-20">
                        <h2 className="text-2xl text-light-blue-800">THOUGHTS</h2>
                        <p className="font-semibold mt-10">I've learned a lot. Here are some of the main things so far:</p>
                        <ul className="list-disc text-slate-500 font-light list-inside">
                            <li>Schema setup - Haven’t needed to set up a schema of this scale before - very useful stuff </li>
                            <li>Backend integration and trpc </li>
                            <li>Typescript. This has given me a great opportunity to learn typescript since we decided to use it for this project.</li>
                            <li>Product design (from a professional large clientelle perspective)
                                <ul className="list-disc list-inside pl-4">
                                    <li>i.e. Really thinking about who we are making this for and how it's going to help them</li>
                                </ul>
                            </li>
                            <li>The importance of understanding and finalizing a user's workflow of the product -
                                it's imperative to having a structured mindset for both designing and engineering 
                            </li>
                        </ul>
                    </div>
                </div>
              </section>
          </main>
      </div>
    )
  }
  
  export default Compass