import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import compasscomputer from '../../public/cards/compass-computer.png';
import WorkNav from '../../components/WorkNav';

function Compass() {
    return (
      <div>
          <Head>
              <title>Hannah McGowan Portfolio</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
  
          <nav className="p-10 max-w-screen-xl flex flex-wrap justify-between mx-auto items-center text-slate-900 dark:text-white">
            <Link href="/"><h1 className="text-xl font-pixel">HM:H+M</h1></Link>
            <div className="w-ful md:block md:w-auto">
              <ul className="flex items-center">
                <li>
                  <BsFillMoonStarsFill 
                  onClick={() => setDarkMode(!darkMode)} 
                  className="cursor-pointer text-2xl"/>
                </li>
                <li><Link href="/work" className="ml-5 font-semibold">Work</Link></li>
                <li><Link href="/about" className="ml-5 font-semibold">About</Link></li>
                <li><Link href="/gallery" className="ml-5 font-semibold">Gallery</Link></li>
              </ul>
            </div>
          </nav>
  
          <main className="px-10 md:px-20 lg:px-40 pb-20 pt-10 w-screen">
              <section className="items-center text-center min-h-screen">
                <div className="pt-5 pb-10">
                    <Image src={compasscomputer} className="object-contain mx-auto" width={650} height={650} alt="example UI of compass app"/>
                </div>
                <div className="px-2 py-4">
                    <h1 className="font-semibold text-3xl">Project Compass with Code for San Francisco</h1>
                    <p className="text-slate-400 text-sm mt-10">An overview of my involvement with Compass - a nonprofit and volunteer driven project founded within Code for San Francisco.</p>
                </div>
              </section>
              {/* breaks up rest of case study between nav and information */}
              <section className="flex">
                {/*<div className="">
                    <ul className="list-none">
                        <p>Nav</p>
                        <li>Overview</li>
                        <li>About</li>
                    </ul>
                </div>*/}
                <WorkNav />
                <div className="flex-grow scroll-smooth">
                    {/* first screen: overview 
                    className="pl-10 h-screen motion-safe:animate-fadeIn"*/}
                    <div id="1" className="pl-10 h-screen motion-safe:animate-fadeIn">
                        <div className="w-full flex justify-between text-sm">
                            <div className="">
                                <p className="font-semibold">Role</p>
                                <p className="">Full Stack Engineer</p>
                            </div>
                            <div className="">
                                <p className="font-semibold">Timeline</p>
                                <p>Jan 2023 - Current</p>
                            </div>
                            <div className="">
                                <p className="font-semibold">Team</p>
                                <p>Compass</p>
                            </div>
                            <div className="">
                                <p className="font-semibold">Tools</p>
                                <p>Next.js, Postgresql, NextAuth, tailwindcss</p>
                            </div>
                        </div>
                        <div className="mt-20">
                            <p className="font-semibold">What is Compass?</p>
                            <p>Compass is a nonprofit and entirely volunteer-led and sustained project 
                                founded within the volunteer brigade, <span class="italic">Code for San Francisco</span>.
                                The founder started the project with the goal of aiding staff within the SFUSD that
                                work with students with disabilities, namely case managers and para professionals. The 
                                application aims to streamline their currently analog process of data collection on 
                                what is referred to as a student's IEP - Individual Education Plan. This would allow staff 
                                to have an easier time keeping track of their students' progress.</p>
                                <br></br>
                            <p>The team is primarily broken up into two subteams - Engineering and Design, although
                                most members (myself included) are simultaneously involved in specific design aspects.
                            </p>
                        </div>
                        <div className="mt-20">
                            <p className="font-semibold">How am I involved?</p>
                            <p>I joined the project as a full stack engineer with an added interest in UI design.</p>
                        </div>
                    </div>
                    <div id="2" className="pl-10 pt-10 h-screen">
                        <div className="w-full flex justify-between">
                            <div className="bg-red-500">
                                <p className="font-semibold">Role</p>
                                <p>Full Stack Engineer</p>
                            </div>
                            <div className="bg-red-500">
                                <p className="font-semibold">Timeline</p>
                                <p>January-Now</p>
                            </div>
                            <div className="bg-red-500">
                                <p className="font-semibold">Team</p>
                                <p>Compass</p>
                            </div>
                            <div className="bg-red-500">
                                <p className="font-semibold">Something</p>
                                <p>Description</p>
                            </div>
                        </div>
                        <div className="mt-20">
                            <p>Overview</p>
                            <p>Lorem ipsum yadaydaydyadydyyaydayyayd</p>
                        </div>
                    </div>
                </div>
              </section>
          </main>
      </div>
    )
  }
  
  export default Compass