import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import cssacomputer from '../../public/cards/cssa-computer.png';
import WorkNav from '../../components/WorkNav';

function Cssa() {
    return (
      <div>
          <Head>
              <title>Hannah McGowan Portfolio</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
  
          <nav className="p-10 max-w-screen-xl flex flex-wrap justify-between mx-auto items-center text-slate-900 dark:text-white">
            <Link href="/"><h1 className="text-xl font-pixel">HM:H+M</h1></Link>
            <div className="w-ful md:block md:w-auto">
              <ul className="flex items-center">
                <li><Link href="/work" className="ml-5 font-semibold">Work</Link></li>
                <li><Link href="/about" className="ml-5 font-semibold">About</Link></li>
                <li><Link href="/gallery" className="ml-5 font-semibold">Gallery</Link></li>
              </ul>
            </div>
          </nav>
  
          <main className="px-5 md:px-20 lg:px-40 pb-20 pt-10 w-screen">
              <section className="items-center text-center min-h-screen">
                <div className="pt-5 pb-10">
                    <Image src={cssacomputer} className="object-contain mx-auto" width={650} height={650} alt="example UI of compass app"/>
                </div>
                <div className="px-2 py-2">
                    <h1 className="font-semibold text-xl md:text-4xl">Berkeley Cogsci Student Association Website Rebuild</h1>
                    <p className="text-slate-400 text-sm mt-10">Rebuild org website from scratch to encapsulate modern design and accessibility of information.</p>
                </div>
              </section>
              {/* breaks up rest of case study between nav and information */}
              <section className="flex">
                <WorkNav />
                <div className="flex-grow">
                    <div className="pl-10 h-screen motion-safe:animate-fadeIn">
                        <div className="w-full flex flex-wrap justify-between text-sm">
                            <div className="">
                                <p className="font-semibold">Role</p>
                                <p>Tech Director</p>
                            </div>
                            <div className="">
                                <p className="font-semibold">Timeline</p>
                                <p>Fall 2021</p>
                            </div>
                            <div className="">
                                <p className="font-semibold">Project</p>
                                <p>For CSSA</p>
                            </div>
                            <div className="">
                                <p className="font-semibold">Tools</p>
                                <p>HTML, CSS, JavaScript, Github</p>
                            </div>
                        </div>
                        <div className="mt-20">
                            <p className="font-semibold">What is Compass?</p>
                            <p>Lorem ipsum yadaydaydyadydyyaydayyayd</p>
                        </div>
                        <div className="mt-20">
                            <p className="font-semibold">How am I involved?</p>
                            <p>I joined the project as a full stack engineer with an added interest in UI design.</p>
                        </div>
                    </div>
                    <div className="pl-10 h-screen">
                        <h2 className="text-2xl text-light-blue-800">ABOUT</h2>
                        <div className="mt-20">
                            <p>Overview</p>
                            <p>Lorem ipsum yadaydaydyadydyyaydayyayd</p>
                        </div>
                    </div>
                </div>
              </section>
          </main>
      </div>
    )
  }
  
  export default Cssa