import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import cssacomputer from '../../public/cards/cssa-computer.png';
import WorkNav from '../../components/WorkNav';
import CssaTabs1 from '../../components/cssa_tabs/CssaTabs1';

function Cssa() {
    return (
      <div>
          <Head>
              <title>Hannah McGowan Portfolio</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
  
          <nav className="p-10 max-w-screen-xl flex flex-wrap justify-between mx-auto items-center text-slate-900 dark:text-white">
            <Link href="/"><h1 className="text-xl font-pixel">HM:H+M</h1></Link>
            <div className="w-ful md:block md:w-auto">
              <ul className="flex items-center">
                <li><Link href="/work" className="ml-5 font-semibold">Work</Link></li>
                <li><Link href="/about" className="ml-5 font-semibold">About</Link></li>
                <li><Link href="/gallery" className="ml-5 font-semibold">Gallery</Link></li>
              </ul>
            </div>
          </nav>
  
          <main className="px-5 md:px-20 lg:px-40 pb-20 pt-10 w-screen">
              <section className="items-center text-center min-h-screen">
                <div className="pt-5 pb-10">
                    <Image src={cssacomputer} className="object-contain mx-auto" width={650} height={650} alt="example UI of compass app"/>
                </div>
                <div className="px-2 py-2">
                    <h1 className="font-semibold text-xl md:text-4xl">Berkeley Cogsci Student Association Website Rebuild</h1>
                    <p className="text-slate-400 text-sm mt-10">Rebuild org website from scratch to encapsulate modern design and accessibility of information.</p>
                </div>
              </section>
              {/* breaks up rest of case study between nav and information */}
              <section className="flex">
                <WorkNav />
                <div className="flex-grow">
                    <div className="pl-10 h-screen motion-safe:animate-fadeIn">
                        <div className="w-full flex flex-wrap justify-between text-sm">
                            <div className="">
                                <p className="font-semibold">Role</p>
                                <p>Tech Director</p>
                            </div>
                            <div className="">
                                <p className="font-semibold">Timeline</p>
                                <p>Fall 2021</p>
                            </div>
                            <div className="">
                                <p className="font-semibold">Project</p>
                                <p>For CSSA</p>
                            </div>
                            <div className="">
                                <p className="font-semibold">Tools</p>
                                <p>HTML, CSS, JS, Github</p>
                            </div>
                        </div>
                        <div className="mt-20">
                            <p className="font-semibold text-slate-900 pb-4">What is CSSA?</p>
                            <p className="text-slate-500 font-light">UC Berkeley’s CSSA is the main undergraduate organization for anyone with an interest in Cognitive Science. 
                                Berkeley CSSA is widely recognized for its hosting of the CCSC - the annual California Cognitive Science Conference. 
                                This conference brings in speakers from around the world who each specialize in one of the disciplines of Cognitive Science at Berkeley - 
                                Psychology, Neuroscience, Computer Science, Linguistics, Philosophy, and Social Sciences or other related fields. 
                                The organization therefore is catered toward a wide variety of people, and hosts many different kinds of events throughout the year.</p>
                        </div>
                        <div className="mt-20 text-slate-500 font-light">
                            <p className="font-semibold text-slate-900 pb-4">What did I do?</p>
                            <p className="pb-3">I joined the CSSA my second year of university. I got elected as the co-Tech Director my third year, during which time 
                                I got acquainted with the former website and made general updates, although 
                                I spent most of my time trying to sift through years worth of files and understand what was actually happening.</p>
                            <p className="pb-3">My senior year I got elected as the sole Tech Director, and decided to take on the challenge of <span className="bg-light-blue-100 p-1 rounded-sm">changing the website for the first time since it’s creation over ten years prior.</span>
                                It was my first attempt tackling every aspect of something at this scale - product design, planning, as well as the actual engineering. </p>
                            <p className="pb-3">My first decision was whether or not to update the existing website to incorporate the new changes or to just start from scratch. 
                                There were <span className="bg-light-blue-100 p-1 rounded-sm">two main reasons why I decided to go all new</span>: there were too many files to even try deleting, and I wanted to adapt the file system to use Github over Filezilla to ensure a more seamless transitioning phase for future Tech Directors. </p>
                            <p className="pb-3">The former website was incredibly informative, but to a fault - there was more than anyone would have the time to read, and much of the information was almost impossible to find. 
                                To paint a picture, some pages were only accessible through a one-word text link in a paragraph at the bottom of an already lengthy page. 
                                Focusing on accessibility of information, ease of presentation, and incorporation of a more distinct color scheme and modern style, the website came to be what it is currently.</p>
                        </div>
                    </div>
                    <div className="pl-10 pt-10 min-h-screen">
                        <h2 className="text-2xl text-light-blue-800">IDEATION & ORGANIZATION</h2>
                        <div>
                            <div className="my-10 text-slate-500 font-light">
                                <p className="font-semibold text-slate-900 pb-2">My Approach</p>
                                <p>This was basically my first big web project for a “client” (somebody other than myself or a class) - so I didn’t know what I was doing. 
                                    I reached out to one alumni for guidance, and they helped immensely with making me realize I needed to narrow down a specific goal statement. 
                                    But other than that, I was on my own. So what did I do?</p>
                                <p>Here’s a breakdown of my younger self’s vision on how to design and build the website:</p>
                            </div>
                            <CssaTabs1 className="mt-10"/>
                        </div>
                    </div>
                    <div className="pl-10 min-h-screen">
                        <h2 className="text-2xl text-light-blue-800">ABOUT</h2>
                        <div className="mt-20">
                            <p>Overview</p>
                            <p>Lorem ipsum yadaydaydyadydyyaydayyayd</p>
                        </div>
                    </div>
                    <div className="pl-10 h-screen">
                        <h2 className="text-2xl text-light-blue-800">ABOUT</h2>
                        <div className="mt-20">
                            <p>Overview</p>
                            <p>Lorem ipsum yadaydaydyadydyyaydayyayd</p>
                        </div>
                    </div>
                    <div className="pl-10 h-screen">
                        <h2 className="text-2xl text-light-blue-800">ABOUT</h2>
                        <div className="mt-20">
                            <p>Overview</p>
                            <p>Lorem ipsum yadaydaydyadydyyaydayyayd</p>
                        </div>
                    </div>
                </div>
              </section>
          </main>
      </div>
    )
  }
  
  export default Cssa