import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import hbcomputer from '../../public/cards/hb-computerG.png';
import hbvisualdesign from '../../public/cards/hb-visualdesign.png';
import hbfigjam from '../../public/cards/hb-figjam.png';
import hbtimeline from '../../public/cards/hb-timeline.png';
import hbinfoarch from '../../public/cards/hb-IA.png';
import hbfigma from '../../public/cards/hb-figma.png';
import hbelementor from '../../public/cards/hb-elementor.png';
import hbusers from '../../public/cards/hb-users.png';
import HbNav from '../../components/navs/HbNav';
import NavMain from '../../components/Nav.js';

function Hopsandbeans() {
    return (
      <div className="scroll-smooth">
          <Head>
              <title>Hannah McGowan Portfolio</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/kirbyicon.png" />
          </Head>

          <NavMain />
          <main className="px-5 md:px-20 lg:px-40 pb-20 pt-10 bg-gray-50">
              <section className="items-center text-center md:min-h-screen pb-10 md:pb-0">
                <div className="pt-5 pb-10">
                    <Image src={hbcomputer} priority={true} className="object-contain mx-auto" width={700} height={700} alt="example UI of compass app"/>
                </div>
                <div className="px-2 py-4">
                    <h1 className="font-semibold text-xl md:text-4xl text-slate-900">Hops & Beans Website</h1>
                    <p className="text-slate-400 text-sm md:text-base mt-10">A case study of a website design and build for Hops & Beans Cafe.</p>
                </div>
              </section>
              {/* breaks up rest of case study between nav and information */}
              <section className="md:flex">
                <HbNav />
                <div className="md:flex-grow">
                    {/* first screen: overview motion-safe:animate-fadeIn */}
                    <div id="1" className="md:pl-10 min-h-screen xl:min-h-0 xl:pb-20">
                        <div className="grid grid-cols-2 gap-4 md:grid-cols-4 text-sm">
                            <div className="text-slate-500 font-light">
                                <p className="font-semibold text-slate-900">Role</p>
                                <p className="">Designer + Developer</p>
                            </div>
                            <div className="text-slate-500 font-light">
                                <p className="font-semibold text-slate-900">Timeline</p>
                                <p>Oct 2023 - March 2024</p>
                            </div>
                            <div className="text-slate-500 font-light">
                                <p className="font-semibold text-slate-900">Client</p>
                                <p>Hops & Beans Cafe</p>
                            </div>
                            <div className="text-slate-500 font-light">
                                <p className="font-semibold text-slate-900">Tools</p>
                                <p>Figma, Figjam, Wordpress, Elementor</p>
                            </div>
                        </div>
                        <div className="mt-20 text-slate-500 font-light">
                            <p className="font-semibold text-slate-900 pb-1">About</p>
                            <p>Hops and Beans is a locally-owned cafe within a historical building that serves coffee, beer, and a great selection of foods. 
                                When I worked there as a barista, the cafe lacked a fully functioning and designed website - so I offered up my skills. 
                                Having an established rapport with the cafe owner and anecdotal experience from the cafe gave me great insight and starting ground 
                                with designing the website. 
                            </p>
                        </div>
                        <div className="mt-10 text-slate-500 font-light">
                            <p className="font-semibold text-slate-900 pb-1">Timeline</p>
                            <div className="pt-5 pb-10">
                                <Image src={hbtimeline} priority={true} className="object-contain md:mx-auto rounded-md" width={900} height={900} alt="Hops & Beans Website Design and Build Timeline"/>
                            </div>
                        </div>
                    </div>

                    <div id="2" className="md:pl-10 pt-10 pb-20">
                        <h2 className="text-2xl text-light-blue-800">CONTENT</h2>
                        <div className="mt-10">
                            <p className="font-semibold text-slate-900 pb-1">The Goal</p>
                            <p className="text-slate-500 font-light">
                                Focus on <span className="underline">ease of use and simplicity</span> while maintaining a <span className="underline">timeless brand aesthetic</span>.
                            </p>
                        </div>
                        <div className="mt-10">
                            <p className="font-semibold text-slate-900 pb-1">The Users & Accessibility</p>
                            <p className="text-slate-500 font-light">
                                Hops & Beans Cafe is locally well-known, and is thus frequented by people of all ages → elderly regulars who come for their 
                                morning coffee, families who eat lunch when the farmers market is open on Sundays, students who come to study, adults who 
                                come to work remotely, or anyone looking to try out a new cafe.
                            </p>
                            <div className="pt-5 pb-10">
                                <Image src={hbusers} priority={true} className="object-contain md:mx-auto rounded-md" width={400} height={400} alt="Hops & Beans Website Information Architecture"/>
                            </div>
                            <p className="text-slate-500 font-light pt-5">
                                With such a diverse target user group, the website had to be <span className="underline">widely marketable</span> and <span className="underline">easily accessible</span> by anyone.
                            </p>
                            <p className="text-slate-500 font-light pt-5">
                                Here are some of the specific design elements that ensured that:
                            </p>
                            <ul className="list-disc pl-10 mt-5 text-slate-500 font-light">
                                <li><span className="font-medium">Spacing:</span> Intentional use of white space to visually aid in the hierarchy and categorization of elements.</li>
                                <li><span className="font-medium">Motion:</span> Limited and simple use of motion in certain elements.</li>
                                <li><span className="font-medium">Color:</span> AAA contrasting color usage.</li>
                                <li><span className="font-medium">Concise:</span> Information is concise and easily navigable.</li>
                            </ul>
                        </div>
                        <div className="mt-10">
                            <p className="font-semibold text-slate-900 pb-1">The Information Architecture</p>
                            <p className="text-slate-500 font-light">The Nav Menu tabs were determined first, and the subsequent important information was funneled into each page accordingly.</p>
                            <div className="pt-5 pb-10">
                                <Image src={hbinfoarch} priority={true} className="object-contain md:mx-auto rounded-md" width={800} height={800} alt="Hops & Beans Website Information Architecture"/>
                            </div>
                        </div>
                    </div>

                    <div id="3" className="md:pl-10 pt-10 min-h-screen pb-20">
                        <h2 className="text-2xl text-light-blue-800">RESEARCH</h2>
                        <div className="mt-10">
                                <p className="font-semibold text-slate-900 pb-1">Competitive Analysis & Moodboards</p>
                                <p className="text-slate-500 font-light">
                                I conducted an informal competitive analysis of a wide variety of other websites ranging from cafes to restaurants to conglomerates and everything in between. 
                                </p>
                                <p className="text-slate-500 font-light pt-5">
                                I compiled a variety of websites with varying styles and layouts into a moodboard to aid in my discussions with the client on determining the direction of the visual design of the website.
                                </p>
                                <div className="pt-5 pb-10">
                                    <Image src={hbfigjam} priority={true} className="object-contain md:mx-auto rounded-md" width={800} height={800} alt="Hops & Beans Website Figjam Moodboard"/>
                                </div>
                        </div> 
                    </div>

                    <div id="4" className="md:pl-10 pt-10 pb-20">
                        <h2 className="text-2xl text-light-blue-800">DESIGN</h2>
                        <div className="mt-10">
                            <p className="font-semibold text-slate-900 pb-1">The Branding</p>
                            <p className="text-slate-500 font-light">
                            Reminder: the design was meant to be timeless in its aesthetic, modern in its design, and somehow encompass the charm of the cafe (or notably its brick exterior). ???????
                            </p>
                        </div>
                        <div className="mt-10">
                            <p className="font-semibold text-slate-900 pb-1">The Visual Design</p>
                            <p className="text-slate-500 font-light">Since this is a volunteer-led project, every member of the team has been intimately involved in each step of the design process.</p>
                            <div className="pt-8 pb-10">
                                <Image src={hbvisualdesign} priority={true} className="object-contain md:mx-auto rounded-md" width={800} height={800} alt="Hops & Beans Website Visual Design Elements"/>
                            </div>
                        </div> 
                    </div>

                    <div id="5" className="md:pl-10 pt-10 pb-20">
                        <h2 className="text-2xl text-light-blue-800">BUILD</h2>
                        <div className="mt-10">
                                <p className="font-semibold text-slate-900 pb-1">Wordpress and Elementor</p>
                                <p className="text-slate-500 font-light">
                                    The original website was built in Wordpress using Elementor, so I familiarized myself with the same platform and started building out each page. 
                                    I added some of the design system components into the platform’s global elements to make the workflow easier. 
                                </p>
                                <p className="text-slate-500 font-light pt-4">
                                    Elementor itself is a fairly intuitive and comprehensive plugin. This made it easier for me to build draft pages using my design mockups, 
                                    and use those pages as prototypes as opposed to building them out in Figma first. 
                                </p>
                                <p className="text-slate-500 font-light pt-4">
                                    Eliminating an extra step of my usual design process greatly improved the efficiency of my workflow, and helped to identify and rule out 
                                    any limitations from the development aspect of the website build simultaneously. 
                                </p>
                        </div>
                        <div className="pt-8 pb-10">
                            <Image src={hbelementor} priority={true} className="object-contain md:mx-auto rounded-md" width={800} height={800} alt="Hops & Beans Website Elementor Workflow"/>
                        </div>
                    </div>
                    <div id="6" className="md:pl-10 pt-10 pb-20">
                        <h2 className="text-2xl text-light-blue-800">THOUGHTS</h2>
                        <p className="font-semibold mt-10">I've learned a lot. Here are some of the main things so far:</p>
                        <ul className="list-disc text-slate-500 font-light pl-3">
                            <li>Schema setup. Haven’t needed to set up a schema of this scale before - very useful stuff </li>
                            <li>Typescript. This has given me a great opportunity to learn typescript since we decided to use it for this project.</li>
                            <li>Product design (from a professional large clientelle perspective)
                                <ul className="list-disc pl-4">
                                    <li>i.e. Really thinking about who we are making this for and how/if it's going to help them</li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
              </section>
          </main>
      </div>
    )
  }
  
  export default Hopsandbeans