import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import hbcomputer from '../../public/cards/hb-computerG.png';
import hbvisualdesign from '../../public/cards/hb-visualdesign.png';
import hbfigjam from '../../public/cards/hb-figjam.png';
import hbtimeline from '../../public/cards/hb-timeline.png';
import hbinfoarch from '../../public/cards/hb-IA.png';
import HbNav from '../../components/navs/HbNav';
import NavMain from '../../components/Nav.js';

function Hopsandbeans() {
    return (
      <div className="scroll-smooth">
          <Head>
              <title>Hannah McGowan Portfolio</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/kirbyicon.png" />
          </Head>

          <NavMain />
          <main className="px-5 md:px-20 lg:px-40 pb-20 pt-10 bg-gray-50">
              <section className="items-center text-center md:min-h-screen pb-10 md:pb-0">
                <div className="pt-5 pb-10">
                    <Image src={hbcomputer} priority={true} className="object-contain mx-auto" width={700} height={700} alt="example UI of compass app"/>
                </div>
                <div className="px-2 py-4">
                    <h1 className="font-semibold text-xl md:text-4xl text-slate-900">Hops & Beans Website</h1>
                    <p className="text-slate-400 text-sm md:text-base mt-10">A case study of a website design and build for Hops & Beans Cafe.</p>
                </div>
              </section>
              {/* breaks up rest of case study between nav and information */}
              <section className="md:flex">
                <HbNav />
                <div className="md:flex-grow">
                    {/* first screen: overview motion-safe:animate-fadeIn */}
                    <div id="1" className="md:pl-10 min-h-screen xl:min-h-0 xl:pb-20">
                        <div className="grid grid-cols-2 gap-4 md:grid-cols-4 text-sm">
                            <div className="text-slate-500 font-light">
                                <p className="font-semibold text-slate-900">Role</p>
                                <p className="">Designer + Developer</p>
                            </div>
                            <div className="text-slate-500 font-light">
                                <p className="font-semibold text-slate-900">Timeline</p>
                                <p>Oct 2023 - Jan 2024</p>
                            </div>
                            <div className="text-slate-500 font-light">
                                <p className="font-semibold text-slate-900">Client</p>
                                <p>Hops & Beans Cafe</p>
                            </div>
                            <div className="text-slate-500 font-light">
                                <p className="font-semibold text-slate-900">Tools</p>
                                <p>Figma, Figjam, Wordpress, Elementor</p>
                            </div>
                        </div>
                        <div className="mt-20 text-slate-500 font-light">
                            <p className="font-semibold text-slate-900 pb-1">About</p>
                            <p>Hops & Beans Cafe is a locally-owned cafe in Fremont, CA. It's located at the oldest commercial building in the city, and serves a great selection of craft coffee, beers, and bites. 
                                While working there as a barista, I reached out to the owner about drafting up a new website for the cafe. 
                            </p>
                        </div>
                        <div className="mt-10 text-slate-500 font-light">
                            <p className="font-semibold text-slate-900 pb-1">Timeline</p>
                            <div className="pt-5 pb-10">
                                <Image src={hbtimeline} priority={true} className="object-contain md:mx-auto rounded-md" width={900} height={900} alt="Hops & Beans Website Visual Design Elements"/>
                            </div>
                        </div>

                    </div>
                    <div>
                        <div id="2" className="md:pl-10 pt-10 pb-20">
                            <h2 className="text-2xl text-light-blue-800">CONTENT</h2>
                            <div className="mt-10">
                                <p className="font-semibold text-slate-900 pb-1">The Goals</p>
                                <p className="text-slate-500 font-light">Since this is a volunteer-led project, every member of the team has been intimately involved in each step of the design process.</p>
                                <ul className="list-disc pl-5">
                                    <li>Make a website that has a consistent brand image</li>
                                    <li>Allow for the display of nice pictures</li>
                                    <li>Keep the website clean and easy to follow</li>
                                </ul>
                            </div>
                            <div className="mt-10">
                                <p className="font-semibold text-slate-900 pb-1">The Users & Accessibility</p>
                                <p className="text-slate-500 font-light">In addition to understanding the perspective of the cafe and what they wanted to portray through the website, we considered who the user base could consist of and how that might affect the design of the website.</p>
                            </div>
                            <div className="mt-10">
                                <p className="font-semibold text-slate-900 pb-1">The Information Architecture</p>
                                <p className="text-slate-500 font-light">Figuring out what the primary navigation menu tabs were going to be was the first step. Based on the owner's idea of the most important elements they wanted to display, we came to an organizational structure as shown below. </p>
                                <div className="pt-5 pb-10">
                                    <Image src={hbinfoarch} priority={true} className="object-contain md:mx-auto rounded-md" width={800} height={800} alt="Hops & Beans Website Visual Design Elements"/>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="3" className="md:pl-10 pt-10 min-h-screen pb-20">
                        <h2 className="text-2xl text-light-blue-800">RESEARCH</h2>
                        <div className="mt-10">
                                <p className="font-semibold text-slate-900 pb-1">The Users & The Problem</p>
                                <p className="text-slate-500 font-light">Compass was created with the intention of aiding the work of staff that work with students with disabilities in the SFUSD. This staff is primarily composed of case managers and paraeducators. Due to lack of funding, there is no digital presence or application that is geared towards managing the process of their IEP goal creation and task delegation. Much of their work is done on paper, which also doesn’t allow for much room or ability to analyze and visualize a student’s progress.</p>
                        </div>
                        <div className="pt-5 pb-10">
                            <Image src={hbfigjam} priority={true} className="object-contain md:mx-auto rounded-md" width={800} height={800} alt="Hops & Beans Website Visual Design Elements"/>
                        </div>
                    </div>
                    <div id="4" className="md:pl-10 pt-10 pb-20">
                        <h2 className="text-2xl text-light-blue-800">DESIGN</h2>
                        <div className="mt-10">
                                <p className="font-semibold text-slate-900 pb-1">The Visual Design</p>
                                <p className="text-slate-500 font-light">Since this is a volunteer-led project, every member of the team has been intimately involved in each step of the design process.</p>
                        </div>
                        <div className="pt-5 pb-10">
                            <Image src={hbvisualdesign} priority={true} className="object-contain md:mx-auto rounded-md" width={800} height={800} alt="Hops & Beans Website Visual Design Elements"/>
                        </div>
                    </div>
                    <div id="5" className="md:pl-10 pt-10 pb-20">
                        <h2 className="text-2xl text-light-blue-800">BUILD</h2>
                        <div className="mt-10">
                                <p className="font-semibold text-slate-900 pb-1">The Branding</p>
                                <p className="text-slate-500 font-light">Since this is a volunteer-led project, every member of the team has been intimately involved in each step of the design process.</p>
                        </div>
                        <div className="pt-5 pb-10">
                            <Image src={hbvisualdesign} priority={true} className="object-contain md:mx-auto rounded-md" width={800} height={800} alt="Hops & Beans Website Visual Design Elements"/>
                        </div>
                    </div>
                    <div id="6" className="md:pl-10 pt-10 pb-20">
                        <h2 className="text-2xl text-light-blue-800">THOUGHTS</h2>
                        <p className="font-semibold mt-10">I've learned a lot. Here are some of the main things so far:</p>
                        <ul className="list-disc text-slate-500 font-light pl-3">
                            <li>Schema setup. Haven’t needed to set up a schema of this scale before - very useful stuff </li>
                            <li>Typescript. This has given me a great opportunity to learn typescript since we decided to use it for this project.</li>
                            <li>Product design (from a professional large clientelle perspective)
                                <ul className="list-disc pl-4">
                                    <li>i.e. Really thinking about who we are making this for and how/if it's going to help them</li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
              </section>
          </main>
      </div>
    )
  }
  
  export default Hopsandbeans