import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import hbcomputer from '../../public/cards/hb-computerG.png';
import hbvisualdesign from '../../public/cards/hb-visualdesign.png';
import CompassNav from '../../components/navs/CompassNav';
import compassds from '../../public/cards/compass-ds.png';
import NavMain from '../../components/Nav.js';

function Hopsandbeans() {
    return (
      <div className="scroll-smooth">
          <Head>
              <title>Hannah McGowan Portfolio</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/kirbyicon.png" />
          </Head>

          <NavMain />
          <main className="px-5 md:px-20 lg:px-40 pb-20 pt-10 bg-gray-50">
              <section className="items-center text-center md:min-h-screen pb-10 md:pb-0">
                <div className="pt-5 pb-10">
                    <Image src={hbcomputer} priority={true} className="object-contain mx-auto" width={700} height={700} alt="example UI of compass app"/>
                </div>
                <div className="px-2 py-4">
                    <h1 className="font-semibold text-xl md:text-4xl text-slate-900">Hops & Beans Website</h1>
                    <p className="text-slate-400 text-sm md:text-base mt-10">A case study of a website design and build for Hops & Beans Cafe.</p>
                </div>
              </section>
              {/* breaks up rest of case study between nav and information */}
              <section className="md:flex">
                <CompassNav />
                <div className="md:flex-grow">
                    {/* first screen: overview motion-safe:animate-fadeIn */}
                    <div id="1" className="md:pl-10 min-h-screen xl:min-h-0 xl:pb-20">
                        <div className="grid grid-cols-2 gap-4 md:grid-cols-4 text-sm">
                            <div className="text-slate-500 font-light">
                                <p className="font-semibold text-slate-900">Role</p>
                                <p className="">Designer + Developer</p>
                            </div>
                            <div className="text-slate-500 font-light">
                                <p className="font-semibold text-slate-900">Timeline</p>
                                <p>Oct 2023 - Jan 2024</p>
                            </div>
                            <div className="text-slate-500 font-light">
                                <p className="font-semibold text-slate-900">Client</p>
                                <p>Hops & Beans Cafe</p>
                            </div>
                            <div className="text-slate-500 font-light">
                                <p className="font-semibold text-slate-900">Tools</p>
                                <p>Figma, Figjam, Wordpress, Elementor</p>
                            </div>
                        </div>
                        <div className="mt-20 text-slate-500 font-light">
                            <p className="font-semibold text-slate-900 pb-1">Overview</p>
                            <p>Hops & Beans Cafe is a locally-owned cafe in Fremont, CA. It's located at the oldest commercial building in the city, and serves a great selection of craft coffee, beers, and bites. 
                                As a former barista working there, I reached out to the owner about drafting up a new website for the cafe. 
                            </p>
                        </div>
                        <div className="mt-10 text-slate-500 font-light">
                            <p className="font-semibold text-slate-900 pb-1">Research & Ideation</p>
                            <p>I set up a meeting to establish initial goals and thoughts about new website. Did competitive analysis on a variety of websites to narrow down the approach. 
                                Used figjam for moodboards which helped to not only establish an overall aesthetic goal but specific design elements as well like typography, colors, and layout.
                            </p>
                        </div>
                        <div className="mt-10 text-slate-500 font-light">
                            <p className="font-semibold text-slate-900 pb-1">Design & Develop</p>
                            <p>The design and development process was very iterative. I would draft up ideas and examples in figma, we would discuss them in meetings, and then I'd incorporate the feedback into the designs. 
                                Once a majority of the design goals were set, especially the information architecture and the layout, I started to build out the pages on Wordpress. 
                                Since I was using elementor, the process was pretty streamlined. I could eliminate the need for a prototype and instead used the actual build to get more feedback on elements like motion, animation, and general navigational feel. 
                            </p>
                            <br></br>
                            <p>
                                Now that the majority of the website is built, we're just waiting on the cafe owner's finalization of a new menu and photos before publising the website.
                            </p>
                        </div>
                    </div>
                    <div>
                        <div id="2" className="md:pl-10 pt-10 pb-20">
                            <h2 className="text-2xl text-light-blue-800">ABOUT</h2>
                            <div className="mt-10">
                                <p className="font-semibold text-slate-900 pb-1">The Branding</p>
                                <p className="text-slate-500 font-light">Since this is a volunteer-led project, every member of the team has been intimately involved in each step of the design process.</p>
                            </div>
                            <div className="pt-5 pb-10">
                                <Image src={hbvisualdesign} priority={true} className="object-contain md:mx-auto rounded-md" width={800} height={800} alt="Hops & Beans Website Visual Design Elements"/>
                            </div>
                            <div className="mt-10">
                                <p className="font-semibold text-slate-900 pb-1">The Users & The Problem</p>
                                <p className="text-slate-500 font-light">Compass was created with the intention of aiding the work of staff that work with students with disabilities in the SFUSD. This staff is primarily composed of case managers and paraeducators. Due to lack of funding, there is no digital presence or application that is geared towards managing the process of their IEP goal creation and task delegation. Much of their work is done on paper, which also doesn’t allow for much room or ability to analyze and visualize a student’s progress.</p>
                            </div>
                            <div className="mt-10">
                                <p className="font-semibold text-slate-900 pb-1">The Solution</p>
                                <p className="text-slate-500 font-light">This application is intended to fill in many of those gaps. It gives case managers a dashboard where they can create IEP goal sheets for their students. They can create tasks and assign them to various paraeducators within the application. This allows them to collect data digitally, which is then stored in a database. That stored data is then visualized in meaningful ways to the case managers, resulting in their students’ progress to be easily accessible and analyzed.</p>
                            </div>
                        </div>
                    </div>
                    <div id="3" className="md:pl-10 pt-10 min-h-screen pb-20">
                        <h2 className="text-2xl text-light-blue-800">WORK</h2>
                        <div>
                            <div className="mt-10 text-slate-500 font-light">
                                <p className="font-semibold text-slate-900 pb-1">Pull requests I’ve made / worked on:</p>
                                <ul className="list-disc pl-3">
                                    <li>Initial setup of the case manager dashboard and user, as well as the general file structure.</li>
                                    <li>Setup of the CSS structure and the continuous incorporation of the design system.</li>
                                    <li>Creation of the sidebar and its mobile adaptation (hamburger menu) for responsive design.</li>
                                </ul>
                            </div>
                        </div>
                        <div className="">
                            <div className="mt-10 text-slate-500 font-light">
                                <p className="font-semibold text-slate-900 pb-1">Approaching from a design perspective</p>
                                <ul className="list-disc pl-3">
                                    <li>Much of the user research and interviews had been done right before I joined the team; the findings from this and subsequent research have been pertinent to our understanding of and motivations for each step of the design process.</li>
                                    <li>The design team is currently working on fleshing out the design system - typography, components, color scheme, layout, logo, etc.</li>
                                    <li>User workflows are broken up into more subteams based on the different users interacting with the app. The application consists of two different faces with varying functionalities, and completely different workflows. One face of the app is geared towards list management for case managers, who assign / delegate tasks to paraprofessionals. They also manage the student IEPs and view the resulting data analysis of the students’ progress. This section is designed to primarily be for a desktop interface. The other face is geared towards a mobile-first interface for the paraprofessionals. Their functionalities generally revolve around completing tasks delegated to them for various students and recording the necessary data. There’s also a third subteam dedicated toward designing the aspects of data collection and visualization; we define why it’s needed and how it will be displayed in the most useful and efficient way.</li>
                                </ul>
                            </div>
                            <div className="md:p-5">
                                <Image src={compassds} className="object-contain md:mx-auto" width={500} height={500} alt="visual design elements for compass"/>
                                <p className="text-center text-slate-500 font-light text-sm">Quick look at the visual design elements.</p>
                            </div>

                        </div>
                    </div>
                    <div id="4" className="md:pl-10 pt-10 pb-20">
                        <h2 className="text-2xl text-light-blue-800">MORE</h2>
                        <p className="font-semibold mt-10">Check back here for screencaps of our finalized designs and initial deployed app!</p>
                    </div>
                    <div id="5" className="md:pl-10 pt-10 pb-20">
                        <h2 className="text-2xl text-light-blue-800">THOUGHTS</h2>
                        <p className="font-semibold mt-10">I've learned a lot. Here are some of the main things so far:</p>
                        <ul className="list-disc text-slate-500 font-light pl-3">
                            <li>Schema setup. Haven’t needed to set up a schema of this scale before - very useful stuff </li>
                            <li>Typescript. This has given me a great opportunity to learn typescript since we decided to use it for this project.</li>
                            <li>Product design (from a professional large clientelle perspective)
                                <ul className="list-disc pl-4">
                                    <li>i.e. Really thinking about who we are making this for and how/if it's going to help them</li>
                                </ul>
                            </li>
                            <li>The importance of understanding and finalizing a user's workflow of the product -
                                it's imperative to having a structured mindset for both designing and engineering 
                                <ul className="list-disc pl-4">
                                    <li>This ties into making sure of scheduling user interviews throughout the build process to gain continuous insight and 
                                        ensure that the product is going in the right direction
                                    </li>
                                </ul>
                            </li>
                            <li>Backend integration and trpc (still trying to understand the depths of how everything works but I never thought 
                                I would've known it at all - just another win in my book) </li>
                        </ul>
                    </div>
                </div>
              </section>
          </main>
      </div>
    )
  }
  
  export default Hopsandbeans