import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import mcgpaintcomputer from '../../public/cards/mcgpaint-computer.png';
import McgNav from '../../components/navs/McgNav';

function Mcgpaint() {
    return (
      <div>
          <Head>
              <title>Hannah McGowan Portfolio</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
  
          <nav className="p-10 max-w-screen-xl flex flex-wrap justify-between mx-auto items-center text-slate-900 dark:text-white">
            <Link href="/"><h1 className="text-xl font-pixel">HM:H+M</h1></Link>
            <div className="w-ful md:block md:w-auto">
              <ul className="flex items-center">
                <li><Link href="/work" className="ml-5 font-semibold hover:text-light-blue-500 active:text-light-blue-800">Work</Link></li>
                <li><Link href="/about" className="ml-5 font-semibold hover:text-light-blue-500 active:text-light-blue-800">About</Link></li>
                <li><Link href="/gallery" className="ml-5 font-semibold hover:text-light-blue-500 active:text-light-blue-800">Gallery</Link></li>
              </ul>
            </div>
          </nav>
  
          <main className="px-5 md:px-20 lg:px-40 pb-20 pt-10 w-screen">
              <section className="items-center text-center min-h-screen">
                <div className="pt-5 pb-10">
                    <Image src={mcgpaintcomputer} className="object-contain mx-auto" width={650} height={650} alt="example UI of compass app"/>
                </div>
                <div className="px-2 py-2">
                    <h1 className="font-semibold text-xl md:text-4xl">McGowan Painting Contracted Website Build</h1>
                    <p className="text-slate-400 text-sm mt-10">Rebuild org website from scratch to encapsulate modern design and accessibility of information.</p>
                </div>
              </section>
              {/* breaks up rest of case study between nav and information */}
              <section className="flex">
                {/*<div className="">
                    <ul className="list-none">
                        <p>Nav</p>
                        <li>Overview</li>
                        <li>About</li>
                    </ul>
                </div>*/}
                <McgNav />
                <div className="flex-grow">
                    {/* first screen: overview 
                    className="pl-10 h-screen motion-safe:animate-fadeIn"*/}
                    <div className="pl-10 h-screen motion-safe:animate-fadeIn">
                        <div className="w-full flex flex-wrap justify-between text-sm">
                            <div className="">
                                <p className="font-semibold">Role</p>
                                <p>Designer & Developer</p>
                            </div>
                            <div className="">
                                <p className="font-semibold">Timeline</p>
                                <p>Couple months</p>
                            </div>
                            <div className="">
                                <p className="font-semibold">Project</p>
                                <p>Commissioned Website</p>
                            </div>
                            <div className="">
                                <p className="font-semibold">Tools</p>
                                <p>HTML, CSS, JS, Figma</p>
                            </div>
                        </div>
                        <h2 className="italic pt-10 text-slate-500">Note: This website is currently in V2. I'll walk through both V1 and V2 in this case study!</h2>
                        <div className="mt-20">
                            <p className="font-semibold">What is McGowan Painting and what did I do?</p>
                            <p>Lorem ipsum yadaydaydyadydyyaydayyayd</p>
                        </div>
                        <div className="mt-20">
                            <p className="font-semibold">How am I involved?</p>
                            <p>I joined the project as a full stack engineer with an added interest in UI design.</p>
                        </div>
                    </div>
                    <div className="pl-10 h-screen">
                        <div className="w-full flex justify-between">
                            <div className="bg-red-500">
                                <p className="font-semibold">Role</p>
                                <p>Full Stack Engineer</p>
                            </div>
                            <div className="bg-red-500">
                                <p className="font-semibold">Timeline</p>
                                <p>January-Now</p>
                            </div>
                            <div className="bg-red-500">
                                <p className="font-semibold">Team</p>
                                <p>Compass</p>
                            </div>
                            <div className="bg-red-500">
                                <p className="font-semibold">Something</p>
                                <p>Description</p>
                            </div>
                        </div>
                        <div className="mt-20">
                            <p>Overview</p>
                            <p>Lorem ipsum yadaydaydyadydyyaydayyayd</p>
                        </div>
                    </div>
                </div>
              </section>
          </main>
      </div>
    )
  }
  
  export default Mcgpaint