import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillLinkedin, AiFillGithub, AiOutlineMail}  from 'react-icons/ai';
import {GrSystem} from 'react-icons/gr';
import {MdWeb} from 'react-icons/md';
import {MdOutlineBrush} from 'react-icons/md';
import {RiListSettingsFill} from 'react-icons/ri';
import Image from 'next/image';
import kirby from '../public/kirbyheadphoneblend.png';
import web4 from '../public/glossier.png';
import web2 from '../public/spotifyalbum.png';
import web3 from '../public/gallery.png';
import web1 from '../public/koss.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import {useState} from 'react';
import PortTabs from './PortTabs.js';




export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Hannah McGowan Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>


      <main className= "bg-white dark:bg-slate-900 px-10 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="pt-10 mb-6 flex justify-between text-slate-900 dark:text-white">
            <h1 className="text-xl font-burtons">HM:H+M</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill 
                onClick={() => setDarkMode(!darkMode)} 
                className="cursor-pointer text-2xl"/>
              </li>
              <li><a href="/resume.pdf" target="_blank" className="bg-gradient-to-r from-cyan-900 to-blue-400 text-white px-4 py-2 rounded-md ml-8">Resume</a></li>
            </ul>
          </nav>
        <div className=" lg:flex place-items-center mt-10" >
          <div classname="w-1/2">
            <div className="text-center p-10">
              <h2 className="text-5xl py-2 text-slate-700 dark:text-slate-300 font-medium md:text-6xl">Hannah McGowan</h2>
              <h3 className="text-2xl py-2 md:text-3xl text-slate-900 dark:text-slate-400">front-end/web developer and designer.</h3>
              <p className="text-md py-5 leading-8 text-slate-500 dark:text-slate-600 md:text-xl max-w-xl mx-auto">Welcome to my website! I showcase past projects and other artworks. Check it out. </p>
            </div>
            <div className="text-5xl flex justify-center gap-16 py-3 text-slate-300  dark:text-slate-600">
              <a href="https://www.linkedin.com/in/hannah-m-74b800120" target="_blank"> <AiFillLinkedin /> </a>
              <a href="https://github.com/hannahmcg" target="_blank">  <AiFillGithub /> </a>
              <a href="mailto:hannahcmcg@berkeley.edu"> <AiOutlineMail /> </a>
            </div>
          </div>
          <div className="relative mx-auto bg-gradient-to-b rounded-full w-1/2 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={kirby} layout="fill" objectFit="cover" />
          </div>
        </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl text-slate-900 py-10  dark:text-slate-300">my experience: design & dev</h3>
            <p className="text-md py-2 leading-8 text-slate-700 dark:text-slate-400">The beginning of my journey 
            as a developer started in my university, doing projects for various classes and organizations. My most notable project in that time was 
            for the <span className="text-blue-400">Cognitive Science Student Association</span>. I also have experience in UI/UX <span className="text-blue-400">
              designing products</span> with other groups. I started with just learning HTML, CSS, and JS from youtube and have since grown accustomed with 
              react, next, tailwind, material tailwind, and continue to look out for the best methods of development. 
            </p>
          </div>
          <div className="lg:flex gap-10 items-center">
            <div className="xl:w-1/3 text-center shadow-lg  dark:shadow-blue-500 p-10 rounded-xl my-10">
              {/*<Image src={design} width={100} height={100} className="mx-auto" />*/}
              <MdOutlineBrush className="mx-auto text-5xl text-slate-800 dark:text-slate-400"/>
              <h3 className="text-lg font-medium pt-8 pb-2 text-slate-900 dark:text-slate-300">innovative designs</h3>
              <p className="py-2 text-slate-800 dark:text-slate-400">create cool designs in a variety of art mediums</p>
              <h4 className="py-4 text-blue-400">design tags</h4>
              <p className="text-slate-500  dark:text-slate-400 py-1">Figma, Adobe XD</p>
              <p className="text-slate-500  dark:text-slate-400 py-1">Illustrator, Photoshop</p>
              <p className="text-slate-500  dark:text-slate-400 py-1">Autodesk Maya, Blender</p>
            </div>
            <div className="xl:w-1/3 text-center shadow-lg dark:shadow-blue-500 p-10 rounded-xl my-10">
              <MdWeb className="mx-auto text-5xl text-slate-800 dark:text-slate-400"/>
              <h3 className="text-lg font-medium pt-8 pb-2 text-slate-900 dark:text-slate-300">frontend apps</h3>
              <p className="py-2 text-slate-800 dark:text-slate-400">build clean designs using modern platforms with UI/UX lense</p>
              <h4 className="py-4 text-blue-400">languages/packages</h4>
              <p className="text-slate-500  dark:text-slate-400 py-1">Javascript, react.js, next.js</p>
              <p className="text-slate-500  dark:text-slate-400 py-1">CSS, tailwindcss, material tw</p>
              <p className="text-slate-500  dark:text-slate-400 py-1">HTML</p>
            </div>
            <div className="xl:w-1/3 text-center shadow-lg  dark:shadow-blue-500 p-10 rounded-xl my-10">
              <RiListSettingsFill className="mx-auto text-5xl text-slate-800 dark:text-slate-400"/>
              <h3 className="text-lg font-medium pt-8 pb-2 text-slate-900 dark:text-slate-300">backend dev</h3>
              <p className="py-2 text-slate-800 dark:text-slate-400">build concise and easily legible code and models</p>
              <h4 className="py-4 text-blue-400">languages</h4>
              <p className="text-slate-500  dark:text-slate-400 py-1">python</p>
              <p className="text-slate-500  dark:text-slate-400 py-1">java</p>
              <p className="text-slate-500  dark:text-slate-400 py-1">SQL, pandas</p>
            </div>
          </div>
        </section>
        <section>
          <div>
             <h3 className="text-3xl py-10 text-slate-900 dark:text-slate-300">portfolio: projects & apps </h3>
             <p className="pt-2 pb-8 leading-8 text-slate-700 dark:text-slate-400">This is my portfolio of web projects and prototypes that I've 
              created and/or developed. Feel free to contact me with any further questions about these projects or my experience overall. Click to get started!
            </p>
            <div className="mb-40">
              <PortTabs />
            </div>
          </div>

          <div>
            <h3 className="text-3xl py-10 text-slate-900 dark:text-slate-300">portfolio: design & artwork </h3>
            <p className="pt-2 pb-8 leading-8 text-slate-700 dark:text-slate-400"> This section showcases various personal UI designs and website redesigns that I've made, as well as other artworks.
            </p>

            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image src={web1} className="rounded-lg object-cover" 
              width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web2} className="rounded-lg object-cover" 
              width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web3} className="rounded-lg object-cover" 
              width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web4} className="rounded-lg object-cover" 
              width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            
          </div>



          </div>


          {/*<div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image src={web1} className="rounded-lg object-cover" 
              width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web2} className="rounded-lg object-cover" 
              width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web3} className="rounded-lg object-cover" 
              width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web4} className="rounded-lg object-cover" 
              width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web5} className="rounded-lg object-cover" 
              width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web6} className="rounded-lg object-cover" 
              width={'100%'} height={'100%'} layout="responsive"/>
            </div>
          </div>*/}

       



         {/* <div className="">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 flex">
              <div>
              <h3 className="text-lg font-medium pt-8 pb-2">cssa</h3>
              <p className="py-2">creating cool designs according to whichever specs</p>
              <h4 className="py-4 text-blue-400">design tags</h4>
              <p className="text-slate-700 py-1">figma</p>
              <p className="text-slate-700 py-1">illustrator</p>
              <p className="text-slate-700 py-1">photoshop</p>
              </div>
              <Image src={mcgpaint} width={400} height={200} className="mx-auto" />
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 flex bg-slate-50">
              <div>
              <h3 className="text-lg font-medium pt-8 pb-2">mcg painting</h3>
              <p className="py-2">creating cool designs according to whichever specs</p>
              <h4 className="py-4 text-blue-400">design tags</h4>
              <p className="text-slate-700 py-1">figma</p>
              <p className="text-slate-700 py-1">illustrator</p>
              <p className="text-slate-700 py-1">photoshop</p>
              </div>
              <Image src={design} width={100} height={100} className="mx-auto" />
            </div>
  </div> */}


        </section>
   
      </main>


    </div>
  )
}
